/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PhigrosApi);
  }
}(this, function(expect, PhigrosApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PhigrosApi.LoginQrCodeApi();
  });

  describe('(package)', function() {
    describe('LoginQrCodeApi', function() {
      describe('phiApiLoginQrCodeCheckQRCodePost', function() {
        it('should call phiApiLoginQrCodeCheckQRCodePost successfully', function(done) {
          // TODO: uncomment, update parameter values for phiApiLoginQrCodeCheckQRCodePost call and complete the assertions
          /*
          var opts = {};

          instance.phiApiLoginQrCodeCheckQRCodePost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PhigrosApi.TapTapTokenDataResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('phiApiLoginQrCodeGetNewQRCodeGet', function() {
        it('should call phiApiLoginQrCodeGetNewQRCodeGet successfully', function(done) {
          // TODO: uncomment, update parameter values for phiApiLoginQrCodeGetNewQRCodeGet call and complete the assertions
          /*
          var opts = {};

          instance.phiApiLoginQrCodeGetNewQRCodeGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PhigrosApi.CompleteQRCodeDataResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('phiApiLoginQrCodeGetPhigrosTokenPost', function() {
        it('should call phiApiLoginQrCodeGetPhigrosTokenPost successfully', function(done) {
          // TODO: uncomment, update parameter values for phiApiLoginQrCodeGetPhigrosTokenPost call and complete the assertions
          /*
          var opts = {};

          instance.phiApiLoginQrCodeGetPhigrosTokenPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PhigrosApi.StringResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('phiApiLoginQrCodeGetTapTapProfilePost', function() {
        it('should call phiApiLoginQrCodeGetTapTapProfilePost successfully', function(done) {
          // TODO: uncomment, update parameter values for phiApiLoginQrCodeGetTapTapProfilePost call and complete the assertions
          /*
          var opts = {};

          instance.phiApiLoginQrCodeGetTapTapProfilePost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PhigrosApi.TapTapProfileDataResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
