/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChallengeLevel
 */
export interface ChallengeLevel {
}

/**
 * Check if a given object implements the ChallengeLevel interface.
 */
export function instanceOfChallengeLevel(value: object): value is ChallengeLevel {
    return true;
}

export function ChallengeLevelFromJSON(json: any): ChallengeLevel {
    return ChallengeLevelFromJSONTyped(json, false);
}

export function ChallengeLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeLevel {
    return json;
}

export function ChallengeLevelToJSON(json: any): ChallengeLevel {
    return ChallengeLevelToJSONTyped(json, false);
}

export function ChallengeLevelToJSONTyped(value?: ChallengeLevel | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

