/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChallengeLevel } from './ChallengeLevel';
import {
    ChallengeLevelFromJSON,
    ChallengeLevelFromJSONTyped,
    ChallengeLevelToJSON,
    ChallengeLevelToJSONTyped,
} from './ChallengeLevel';
import type { ChallengeRawCode } from './ChallengeRawCode';
import {
    ChallengeRawCodeFromJSON,
    ChallengeRawCodeFromJSONTyped,
    ChallengeRawCodeToJSON,
    ChallengeRawCodeToJSONTyped,
} from './ChallengeRawCode';

/**
 * 
 * @export
 * @interface Challenge
 */
export interface Challenge {
    /**
     * 
     * @type {ChallengeRawCode}
     * @memberof Challenge
     */
    rawCode?: ChallengeRawCode;
    /**
     * 
     * @type {number}
     * @memberof Challenge
     */
    rank?: number;
    /**
     * 
     * @type {ChallengeLevel}
     * @memberof Challenge
     */
    level?: ChallengeLevel;
    /**
     * 
     * @type {boolean}
     * @memberof Challenge
     */
    hasEverDone?: boolean;
}

/**
 * Check if a given object implements the Challenge interface.
 */
export function instanceOfChallenge(value: object): value is Challenge {
    return true;
}

export function ChallengeFromJSON(json: any): Challenge {
    return ChallengeFromJSONTyped(json, false);
}

export function ChallengeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Challenge {
    if (json == null) {
        return json;
    }
    return {
        
        'rawCode': json['rawCode'] == null ? undefined : ChallengeRawCodeFromJSON(json['rawCode']),
        'rank': json['rank'] == null ? undefined : json['rank'],
        'level': json['level'] == null ? undefined : ChallengeLevelFromJSON(json['level']),
        'hasEverDone': json['hasEverDone'] == null ? undefined : json['hasEverDone'],
    };
}

export function ChallengeToJSON(json: any): Challenge {
    return ChallengeToJSONTyped(json, false);
}

export function ChallengeToJSONTyped(value?: Challenge | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rawCode': ChallengeRawCodeToJSON(value['rawCode']),
        'rank': value['rank'],
        'level': ChallengeLevelToJSON(value['level']),
        'hasEverDone': value['hasEverDone'],
    };
}

