/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChallengeRawCode
 */
export interface ChallengeRawCode {
}

/**
 * Check if a given object implements the ChallengeRawCode interface.
 */
export function instanceOfChallengeRawCode(value: object): value is ChallengeRawCode {
    return true;
}

export function ChallengeRawCodeFromJSON(json: any): ChallengeRawCode {
    return ChallengeRawCodeFromJSONTyped(json, false);
}

export function ChallengeRawCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeRawCode {
    return json;
}

export function ChallengeRawCodeToJSON(json: any): ChallengeRawCode {
    return ChallengeRawCodeToJSONTyped(json, false);
}

export function ChallengeRawCodeToJSONTyped(value?: ChallengeRawCode | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

