/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompleteScoreChartConstant
 */
export interface CompleteScoreChartConstant {
}

/**
 * Check if a given object implements the CompleteScoreChartConstant interface.
 */
export function instanceOfCompleteScoreChartConstant(value: object): value is CompleteScoreChartConstant {
    return true;
}

export function CompleteScoreChartConstantFromJSON(json: any): CompleteScoreChartConstant {
    return CompleteScoreChartConstantFromJSONTyped(json, false);
}

export function CompleteScoreChartConstantFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompleteScoreChartConstant {
    return json;
}

export function CompleteScoreChartConstantToJSON(json: any): CompleteScoreChartConstant {
    return CompleteScoreChartConstantToJSONTyped(json, false);
}

export function CompleteScoreChartConstantToJSONTyped(value?: CompleteScoreChartConstant | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

