/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompleteScoreRks
 */
export interface CompleteScoreRks {
}

/**
 * Check if a given object implements the CompleteScoreRks interface.
 */
export function instanceOfCompleteScoreRks(value: object): value is CompleteScoreRks {
    return true;
}

export function CompleteScoreRksFromJSON(json: any): CompleteScoreRks {
    return CompleteScoreRksFromJSONTyped(json, false);
}

export function CompleteScoreRksFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompleteScoreRks {
    return json;
}

export function CompleteScoreRksToJSON(json: any): CompleteScoreRks {
    return CompleteScoreRksToJSONTyped(json, false);
}

export function CompleteScoreRksToJSONTyped(value?: CompleteScoreRks | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

