/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompleteScoreChartConstant } from './CompleteScoreChartConstant';
import {
    CompleteScoreChartConstantFromJSON,
    CompleteScoreChartConstantFromJSONTyped,
    CompleteScoreChartConstantToJSON,
    CompleteScoreChartConstantToJSONTyped,
} from './CompleteScoreChartConstant';
import type { CompleteScoreRks } from './CompleteScoreRks';
import {
    CompleteScoreRksFromJSON,
    CompleteScoreRksFromJSONTyped,
    CompleteScoreRksToJSON,
    CompleteScoreRksToJSONTyped,
} from './CompleteScoreRks';
import type { SongScore } from './SongScore';
import {
    SongScoreFromJSON,
    SongScoreFromJSONTyped,
    SongScoreToJSON,
    SongScoreToJSONTyped,
} from './SongScore';

/**
 * 
 * @export
 * @interface CompleteScore
 */
export interface CompleteScore {
    /**
     * 
     * @type {SongScore}
     * @memberof CompleteScore
     */
    score?: SongScore;
    /**
     * 
     * @type {string}
     * @memberof CompleteScore
     */
    nameOrDefault?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CompleteScore
     */
    name?: string | null;
    /**
     * 
     * @type {CompleteScoreChartConstant}
     * @memberof CompleteScore
     */
    chartConstant?: CompleteScoreChartConstant;
    /**
     * 
     * @type {CompleteScoreRks}
     * @memberof CompleteScore
     */
    rks?: CompleteScoreRks;
}

/**
 * Check if a given object implements the CompleteScore interface.
 */
export function instanceOfCompleteScore(value: object): value is CompleteScore {
    return true;
}

export function CompleteScoreFromJSON(json: any): CompleteScore {
    return CompleteScoreFromJSONTyped(json, false);
}

export function CompleteScoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompleteScore {
    if (json == null) {
        return json;
    }
    return {
        
        'score': json['score'] == null ? undefined : SongScoreFromJSON(json['score']),
        'nameOrDefault': json['nameOrDefault'] === undefined ? undefined : json['nameOrDefault'] === null ? null : json['nameOrDefault'],
        'name': json['name'] === undefined ? undefined : json['name'] === null ? null : json['name'],
        'chartConstant': json['chartConstant'] == null ? undefined : CompleteScoreChartConstantFromJSON(json['chartConstant']),
        'rks': json['rks'] == null ? undefined : CompleteScoreRksFromJSON(json['rks']),
    };
}

export function CompleteScoreToJSON(json: any): CompleteScore {
    return CompleteScoreToJSONTyped(json, false);
}

export function CompleteScoreToJSONTyped(value?: CompleteScore | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'score': SongScoreToJSON(value['score']),
        'nameOrDefault': value['nameOrDefault'],
        'name': value['name'],
        'chartConstant': CompleteScoreChartConstantToJSON(value['chartConstant']),
        'rks': CompleteScoreRksToJSON(value['rks']),
    };
}

