/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
    MoneyToJSONTyped,
} from './Money';
import type { ChallengeLevel } from './ChallengeLevel';
import {
    ChallengeLevelFromJSON,
    ChallengeLevelFromJSONTyped,
    ChallengeLevelToJSON,
    ChallengeLevelToJSONTyped,
} from './ChallengeLevel';
import type { PhiApiCloudSaveGetSaveDataPostIndexParameter } from './PhiApiCloudSaveGetSaveDataPostIndexParameter';
import {
    PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSON,
    PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSONTyped,
    PhiApiCloudSaveGetSaveDataPostIndexParameterToJSON,
    PhiApiCloudSaveGetSaveDataPostIndexParameterToJSONTyped,
} from './PhiApiCloudSaveGetSaveDataPostIndexParameter';
import type { Challenge } from './Challenge';
import {
    ChallengeFromJSON,
    ChallengeFromJSONTyped,
    ChallengeToJSON,
    ChallengeToJSONTyped,
} from './Challenge';
import type { GameProgressNodeVersion2 } from './GameProgressNodeVersion2';
import {
    GameProgressNodeVersion2FromJSON,
    GameProgressNodeVersion2FromJSONTyped,
    GameProgressNodeVersion2ToJSON,
    GameProgressNodeVersion2ToJSONTyped,
} from './GameProgressNodeVersion2';

/**
 * 
 * @export
 * @interface GameProgress
 */
export interface GameProgress {
    /**
     * 
     * @type {ChallengeLevel}
     * @memberof GameProgress
     */
    version: ChallengeLevel;
    /**
     * 
     * @type {boolean}
     * @memberof GameProgress
     */
    isFirstRun: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GameProgress
     */
    legacyChapterFinished: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GameProgress
     */
    alreadyShowCollectionTip: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GameProgress
     */
    alreadyShowAutoUnlockINTip: boolean;
    /**
     * 
     * @type {string}
     * @memberof GameProgress
     */
    gameCompleted?: string;
    /**
     * 
     * @type {PhiApiCloudSaveGetSaveDataPostIndexParameter}
     * @memberof GameProgress
     */
    songUpdateInfo: PhiApiCloudSaveGetSaveDataPostIndexParameter;
    /**
     * 
     * @type {Challenge}
     * @memberof GameProgress
     */
    challengeModeRank: Challenge;
    /**
     * 
     * @type {Money}
     * @memberof GameProgress
     */
    money: Money;
    /**
     * 
     * @type {number}
     * @memberof GameProgress
     */
    unlockFlagOfSpasmodic: number;
    /**
     * 
     * @type {number}
     * @memberof GameProgress
     */
    unlockFlagOfIgallta: number;
    /**
     * 
     * @type {number}
     * @memberof GameProgress
     */
    unlockFlagOfRrharil: number;
    /**
     * 
     * @type {number}
     * @memberof GameProgress
     */
    flagOfSongRecordKey: number;
    /**
     * 
     * @type {GameProgressNodeVersion2}
     * @memberof GameProgress
     */
    node2: GameProgressNodeVersion2 | null;
}

/**
 * Check if a given object implements the GameProgress interface.
 */
export function instanceOfGameProgress(value: object): value is GameProgress {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('isFirstRun' in value) || value['isFirstRun'] === undefined) return false;
    if (!('legacyChapterFinished' in value) || value['legacyChapterFinished'] === undefined) return false;
    if (!('alreadyShowCollectionTip' in value) || value['alreadyShowCollectionTip'] === undefined) return false;
    if (!('alreadyShowAutoUnlockINTip' in value) || value['alreadyShowAutoUnlockINTip'] === undefined) return false;
    if (!('songUpdateInfo' in value) || value['songUpdateInfo'] === undefined) return false;
    if (!('challengeModeRank' in value) || value['challengeModeRank'] === undefined) return false;
    if (!('money' in value) || value['money'] === undefined) return false;
    if (!('unlockFlagOfSpasmodic' in value) || value['unlockFlagOfSpasmodic'] === undefined) return false;
    if (!('unlockFlagOfIgallta' in value) || value['unlockFlagOfIgallta'] === undefined) return false;
    if (!('unlockFlagOfRrharil' in value) || value['unlockFlagOfRrharil'] === undefined) return false;
    if (!('flagOfSongRecordKey' in value) || value['flagOfSongRecordKey'] === undefined) return false;
    if (!('node2' in value) || value['node2'] === undefined) return false;
    return true;
}

export function GameProgressFromJSON(json: any): GameProgress {
    return GameProgressFromJSONTyped(json, false);
}

export function GameProgressFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameProgress {
    if (json == null) {
        return json;
    }
    return {
        
        'version': ChallengeLevelFromJSON(json['version']),
        'isFirstRun': json['isFirstRun'],
        'legacyChapterFinished': json['legacyChapterFinished'],
        'alreadyShowCollectionTip': json['alreadyShowCollectionTip'],
        'alreadyShowAutoUnlockINTip': json['alreadyShowAutoUnlockINTip'],
        'gameCompleted': json['gameCompleted'] == null ? undefined : json['gameCompleted'],
        'songUpdateInfo': PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSON(json['songUpdateInfo']),
        'challengeModeRank': ChallengeFromJSON(json['challengeModeRank']),
        'money': MoneyFromJSON(json['money']),
        'unlockFlagOfSpasmodic': json['unlockFlagOfSpasmodic'],
        'unlockFlagOfIgallta': json['unlockFlagOfIgallta'],
        'unlockFlagOfRrharil': json['unlockFlagOfRrharil'],
        'flagOfSongRecordKey': json['flagOfSongRecordKey'],
        'node2': GameProgressNodeVersion2FromJSON(json['node2']),
    };
}

export function GameProgressToJSON(json: any): GameProgress {
    return GameProgressToJSONTyped(json, false);
}

export function GameProgressToJSONTyped(value?: GameProgress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': ChallengeLevelToJSON(value['version']),
        'isFirstRun': value['isFirstRun'],
        'legacyChapterFinished': value['legacyChapterFinished'],
        'alreadyShowCollectionTip': value['alreadyShowCollectionTip'],
        'alreadyShowAutoUnlockINTip': value['alreadyShowAutoUnlockINTip'],
        'gameCompleted': value['gameCompleted'],
        'songUpdateInfo': PhiApiCloudSaveGetSaveDataPostIndexParameterToJSON(value['songUpdateInfo']),
        'challengeModeRank': ChallengeToJSON(value['challengeModeRank']),
        'money': MoneyToJSON(value['money']),
        'unlockFlagOfSpasmodic': value['unlockFlagOfSpasmodic'],
        'unlockFlagOfIgallta': value['unlockFlagOfIgallta'],
        'unlockFlagOfRrharil': value['unlockFlagOfRrharil'],
        'flagOfSongRecordKey': value['flagOfSongRecordKey'],
        'node2': GameProgressNodeVersion2ToJSON(value['node2']),
    };
}

