/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameProgressNodeVersion4 } from './GameProgressNodeVersion4';
import {
    GameProgressNodeVersion4FromJSON,
    GameProgressNodeVersion4FromJSONTyped,
    GameProgressNodeVersion4ToJSON,
    GameProgressNodeVersion4ToJSONTyped,
} from './GameProgressNodeVersion4';

/**
 * 
 * @export
 * @interface GameProgressNodeVersion3
 */
export interface GameProgressNodeVersion3 {
    /**
     * 
     * @type {number}
     * @memberof GameProgressNodeVersion3
     */
    chapter8UnlockFlag: number;
    /**
     * 
     * @type {number}
     * @memberof GameProgressNodeVersion3
     */
    chapter8SongUnlockFlag: number;
    /**
     * 
     * @type {GameProgressNodeVersion4}
     * @memberof GameProgressNodeVersion3
     */
    node4: GameProgressNodeVersion4 | null;
}

/**
 * Check if a given object implements the GameProgressNodeVersion3 interface.
 */
export function instanceOfGameProgressNodeVersion3(value: object): value is GameProgressNodeVersion3 {
    if (!('chapter8UnlockFlag' in value) || value['chapter8UnlockFlag'] === undefined) return false;
    if (!('chapter8SongUnlockFlag' in value) || value['chapter8SongUnlockFlag'] === undefined) return false;
    if (!('node4' in value) || value['node4'] === undefined) return false;
    return true;
}

export function GameProgressNodeVersion3FromJSON(json: any): GameProgressNodeVersion3 {
    return GameProgressNodeVersion3FromJSONTyped(json, false);
}

export function GameProgressNodeVersion3FromJSONTyped(json: any, ignoreDiscriminator: boolean): GameProgressNodeVersion3 {
    if (json == null) {
        return json;
    }
    return {
        
        'chapter8UnlockFlag': json['chapter8UnlockFlag'],
        'chapter8SongUnlockFlag': json['chapter8SongUnlockFlag'],
        'node4': GameProgressNodeVersion4FromJSON(json['node4']),
    };
}

export function GameProgressNodeVersion3ToJSON(json: any): GameProgressNodeVersion3 {
    return GameProgressNodeVersion3ToJSONTyped(json, false);
}

export function GameProgressNodeVersion3ToJSONTyped(value?: GameProgressNodeVersion3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chapter8UnlockFlag': value['chapter8UnlockFlag'],
        'chapter8SongUnlockFlag': value['chapter8SongUnlockFlag'],
        'node4': GameProgressNodeVersion4ToJSON(value['node4']),
    };
}

