/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChallengeLevel } from './ChallengeLevel';
import {
    ChallengeLevelFromJSON,
    ChallengeLevelFromJSONTyped,
    ChallengeLevelToJSON,
    ChallengeLevelToJSONTyped,
} from './ChallengeLevel';

/**
 * 
 * @export
 * @interface GameUserInfo
 */
export interface GameUserInfo {
    /**
     * 
     * @type {ChallengeLevel}
     * @memberof GameUserInfo
     */
    version: ChallengeLevel;
    /**
     * 
     * @type {boolean}
     * @memberof GameUserInfo
     */
    showUserId: boolean;
    /**
     * 
     * @type {string}
     * @memberof GameUserInfo
     */
    intro: string;
    /**
     * 
     * @type {string}
     * @memberof GameUserInfo
     */
    avatarId: string;
    /**
     * 
     * @type {string}
     * @memberof GameUserInfo
     */
    backgroundId: string;
}

/**
 * Check if a given object implements the GameUserInfo interface.
 */
export function instanceOfGameUserInfo(value: object): value is GameUserInfo {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('showUserId' in value) || value['showUserId'] === undefined) return false;
    if (!('intro' in value) || value['intro'] === undefined) return false;
    if (!('avatarId' in value) || value['avatarId'] === undefined) return false;
    if (!('backgroundId' in value) || value['backgroundId'] === undefined) return false;
    return true;
}

export function GameUserInfoFromJSON(json: any): GameUserInfo {
    return GameUserInfoFromJSONTyped(json, false);
}

export function GameUserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameUserInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'version': ChallengeLevelFromJSON(json['version']),
        'showUserId': json['showUserId'],
        'intro': json['intro'],
        'avatarId': json['avatarId'],
        'backgroundId': json['backgroundId'],
    };
}

export function GameUserInfoToJSON(json: any): GameUserInfo {
    return GameUserInfoToJSONTyped(json, false);
}

export function GameUserInfoToJSONTyped(value?: GameUserInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': ChallengeLevelToJSON(value['version']),
        'showUserId': value['showUserId'],
        'intro': value['intro'],
        'avatarId': value['avatarId'],
        'backgroundId': value['backgroundId'],
    };
}

