/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GameProgressNodeVersion4
 */
export interface GameProgressNodeVersion4 {
    /**
     * 
     * @type {number}
     * @memberof GameProgressNodeVersion4
     */
    flagOfSongRecordKeyTakumi: number;
}

/**
 * Check if a given object implements the GameProgressNodeVersion4 interface.
 */
export function instanceOfGameProgressNodeVersion4(value: object): value is GameProgressNodeVersion4 {
    if (!('flagOfSongRecordKeyTakumi' in value) || value['flagOfSongRecordKeyTakumi'] === undefined) return false;
    return true;
}

export function GameProgressNodeVersion4FromJSON(json: any): GameProgressNodeVersion4 {
    return GameProgressNodeVersion4FromJSONTyped(json, false);
}

export function GameProgressNodeVersion4FromJSONTyped(json: any, ignoreDiscriminator: boolean): GameProgressNodeVersion4 {
    if (json == null) {
        return json;
    }
    return {
        
        'flagOfSongRecordKeyTakumi': json['flagOfSongRecordKeyTakumi'],
    };
}

export function GameProgressNodeVersion4ToJSON(json: any): GameProgressNodeVersion4 {
    return GameProgressNodeVersion4ToJSONTyped(json, false);
}

export function GameProgressNodeVersion4ToJSONTyped(value?: GameProgressNodeVersion4 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'flagOfSongRecordKeyTakumi': value['flagOfSongRecordKeyTakumi'],
    };
}

