/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameProgressNodeVersion3 } from './GameProgressNodeVersion3';
import {
    GameProgressNodeVersion3FromJSON,
    GameProgressNodeVersion3FromJSONTyped,
    GameProgressNodeVersion3ToJSON,
    GameProgressNodeVersion3ToJSONTyped,
} from './GameProgressNodeVersion3';

/**
 * 
 * @export
 * @interface GameProgressNodeVersion2
 */
export interface GameProgressNodeVersion2 {
    /**
     * 
     * @type {number}
     * @memberof GameProgressNodeVersion2
     */
    randomVersionUnlocked: number;
    /**
     * 
     * @type {GameProgressNodeVersion3}
     * @memberof GameProgressNodeVersion2
     */
    node3: GameProgressNodeVersion3 | null;
}

/**
 * Check if a given object implements the GameProgressNodeVersion2 interface.
 */
export function instanceOfGameProgressNodeVersion2(value: object): value is GameProgressNodeVersion2 {
    if (!('randomVersionUnlocked' in value) || value['randomVersionUnlocked'] === undefined) return false;
    if (!('node3' in value) || value['node3'] === undefined) return false;
    return true;
}

export function GameProgressNodeVersion2FromJSON(json: any): GameProgressNodeVersion2 {
    return GameProgressNodeVersion2FromJSONTyped(json, false);
}

export function GameProgressNodeVersion2FromJSONTyped(json: any, ignoreDiscriminator: boolean): GameProgressNodeVersion2 {
    if (json == null) {
        return json;
    }
    return {
        
        'randomVersionUnlocked': json['randomVersionUnlocked'],
        'node3': GameProgressNodeVersion3FromJSON(json['node3']),
    };
}

export function GameProgressNodeVersion2ToJSON(json: any): GameProgressNodeVersion2 {
    return GameProgressNodeVersion2ToJSONTyped(json, false);
}

export function GameProgressNodeVersion2ToJSONTyped(value?: GameProgressNodeVersion2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'randomVersionUnlocked': value['randomVersionUnlocked'],
        'node3': GameProgressNodeVersion3ToJSON(value['node3']),
    };
}

