/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompleteScoreChartConstant } from './CompleteScoreChartConstant';
import {
    CompleteScoreChartConstantFromJSON,
    CompleteScoreChartConstantFromJSONTyped,
    CompleteScoreChartConstantToJSON,
    CompleteScoreChartConstantToJSONTyped,
} from './CompleteScoreChartConstant';
import type { ChallengeLevel } from './ChallengeLevel';
import {
    ChallengeLevelFromJSON,
    ChallengeLevelFromJSONTyped,
    ChallengeLevelToJSON,
    ChallengeLevelToJSONTyped,
} from './ChallengeLevel';

/**
 * 
 * @export
 * @interface GameSettings
 */
export interface GameSettings {
    /**
     * 
     * @type {ChallengeLevel}
     * @memberof GameSettings
     */
    version: ChallengeLevel;
    /**
     * 
     * @type {boolean}
     * @memberof GameSettings
     */
    chordSupport: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GameSettings
     */
    fcApIndicatorOn: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GameSettings
     */
    enableHitSound: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GameSettings
     */
    lowResolutionModeOn: boolean;
    /**
     * 
     * @type {string}
     * @memberof GameSettings
     */
    deviceName: string;
    /**
     * 
     * @type {CompleteScoreChartConstant}
     * @memberof GameSettings
     */
    backgroundBrightness: CompleteScoreChartConstant;
    /**
     * 
     * @type {CompleteScoreChartConstant}
     * @memberof GameSettings
     */
    musicVolume: CompleteScoreChartConstant;
    /**
     * 
     * @type {CompleteScoreChartConstant}
     * @memberof GameSettings
     */
    effectVolume: CompleteScoreChartConstant;
    /**
     * 
     * @type {CompleteScoreChartConstant}
     * @memberof GameSettings
     */
    hitSoundVolume: CompleteScoreChartConstant;
    /**
     * 
     * @type {CompleteScoreChartConstant}
     * @memberof GameSettings
     */
    soundOffset: CompleteScoreChartConstant;
    /**
     * 
     * @type {CompleteScoreChartConstant}
     * @memberof GameSettings
     */
    noteScale: CompleteScoreChartConstant;
}

/**
 * Check if a given object implements the GameSettings interface.
 */
export function instanceOfGameSettings(value: object): value is GameSettings {
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('chordSupport' in value) || value['chordSupport'] === undefined) return false;
    if (!('fcApIndicatorOn' in value) || value['fcApIndicatorOn'] === undefined) return false;
    if (!('enableHitSound' in value) || value['enableHitSound'] === undefined) return false;
    if (!('lowResolutionModeOn' in value) || value['lowResolutionModeOn'] === undefined) return false;
    if (!('deviceName' in value) || value['deviceName'] === undefined) return false;
    if (!('backgroundBrightness' in value) || value['backgroundBrightness'] === undefined) return false;
    if (!('musicVolume' in value) || value['musicVolume'] === undefined) return false;
    if (!('effectVolume' in value) || value['effectVolume'] === undefined) return false;
    if (!('hitSoundVolume' in value) || value['hitSoundVolume'] === undefined) return false;
    if (!('soundOffset' in value) || value['soundOffset'] === undefined) return false;
    if (!('noteScale' in value) || value['noteScale'] === undefined) return false;
    return true;
}

export function GameSettingsFromJSON(json: any): GameSettings {
    return GameSettingsFromJSONTyped(json, false);
}

export function GameSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'version': ChallengeLevelFromJSON(json['version']),
        'chordSupport': json['chordSupport'],
        'fcApIndicatorOn': json['fcApIndicatorOn'],
        'enableHitSound': json['enableHitSound'],
        'lowResolutionModeOn': json['lowResolutionModeOn'],
        'deviceName': json['deviceName'],
        'backgroundBrightness': CompleteScoreChartConstantFromJSON(json['backgroundBrightness']),
        'musicVolume': CompleteScoreChartConstantFromJSON(json['musicVolume']),
        'effectVolume': CompleteScoreChartConstantFromJSON(json['effectVolume']),
        'hitSoundVolume': CompleteScoreChartConstantFromJSON(json['hitSoundVolume']),
        'soundOffset': CompleteScoreChartConstantFromJSON(json['soundOffset']),
        'noteScale': CompleteScoreChartConstantFromJSON(json['noteScale']),
    };
}

export function GameSettingsToJSON(json: any): GameSettings {
    return GameSettingsToJSONTyped(json, false);
}

export function GameSettingsToJSONTyped(value?: GameSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': ChallengeLevelToJSON(value['version']),
        'chordSupport': value['chordSupport'],
        'fcApIndicatorOn': value['fcApIndicatorOn'],
        'enableHitSound': value['enableHitSound'],
        'lowResolutionModeOn': value['lowResolutionModeOn'],
        'deviceName': value['deviceName'],
        'backgroundBrightness': CompleteScoreChartConstantToJSON(value['backgroundBrightness']),
        'musicVolume': CompleteScoreChartConstantToJSON(value['musicVolume']),
        'effectVolume': CompleteScoreChartConstantToJSON(value['effectVolume']),
        'hitSoundVolume': CompleteScoreChartConstantToJSON(value['hitSoundVolume']),
        'soundOffset': CompleteScoreChartConstantToJSON(value['soundOffset']),
        'noteScale': CompleteScoreChartConstantToJSON(value['noteScale']),
    };
}

