/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PhiApiCloudSaveGetSaveDataPostIndexParameter } from './PhiApiCloudSaveGetSaveDataPostIndexParameter';
import {
    PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSON,
    PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSONTyped,
    PhiApiCloudSaveGetSaveDataPostIndexParameterToJSON,
    PhiApiCloudSaveGetSaveDataPostIndexParameterToJSONTyped,
} from './PhiApiCloudSaveGetSaveDataPostIndexParameter';

/**
 * 
 * @export
 * @interface Money
 */
export interface Money {
    /**
     * 
     * @type {PhiApiCloudSaveGetSaveDataPostIndexParameter}
     * @memberof Money
     */
    kiB: PhiApiCloudSaveGetSaveDataPostIndexParameter;
    /**
     * 
     * @type {PhiApiCloudSaveGetSaveDataPostIndexParameter}
     * @memberof Money
     */
    miB: PhiApiCloudSaveGetSaveDataPostIndexParameter;
    /**
     * 
     * @type {PhiApiCloudSaveGetSaveDataPostIndexParameter}
     * @memberof Money
     */
    giB: PhiApiCloudSaveGetSaveDataPostIndexParameter;
    /**
     * 
     * @type {PhiApiCloudSaveGetSaveDataPostIndexParameter}
     * @memberof Money
     */
    tiB: PhiApiCloudSaveGetSaveDataPostIndexParameter;
    /**
     * 
     * @type {PhiApiCloudSaveGetSaveDataPostIndexParameter}
     * @memberof Money
     */
    piB: PhiApiCloudSaveGetSaveDataPostIndexParameter;
}

/**
 * Check if a given object implements the Money interface.
 */
export function instanceOfMoney(value: object): value is Money {
    if (!('kiB' in value) || value['kiB'] === undefined) return false;
    if (!('miB' in value) || value['miB'] === undefined) return false;
    if (!('giB' in value) || value['giB'] === undefined) return false;
    if (!('tiB' in value) || value['tiB'] === undefined) return false;
    if (!('piB' in value) || value['piB'] === undefined) return false;
    return true;
}

export function MoneyFromJSON(json: any): Money {
    return MoneyFromJSONTyped(json, false);
}

export function MoneyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Money {
    if (json == null) {
        return json;
    }
    return {
        
        'kiB': PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSON(json['kiB']),
        'miB': PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSON(json['miB']),
        'giB': PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSON(json['giB']),
        'tiB': PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSON(json['tiB']),
        'piB': PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSON(json['piB']),
    };
}

export function MoneyToJSON(json: any): Money {
    return MoneyToJSONTyped(json, false);
}

export function MoneyToJSONTyped(value?: Money | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kiB': PhiApiCloudSaveGetSaveDataPostIndexParameterToJSON(value['kiB']),
        'miB': PhiApiCloudSaveGetSaveDataPostIndexParameterToJSON(value['miB']),
        'giB': PhiApiCloudSaveGetSaveDataPostIndexParameterToJSON(value['giB']),
        'tiB': PhiApiCloudSaveGetSaveDataPostIndexParameterToJSON(value['tiB']),
        'piB': PhiApiCloudSaveGetSaveDataPostIndexParameterToJSON(value['piB']),
    };
}

