/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PhiApiCloudSaveGetSaveDataPostIndexParameter } from './PhiApiCloudSaveGetSaveDataPostIndexParameter';
import {
    PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSON,
    PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSONTyped,
    PhiApiCloudSaveGetSaveDataPostIndexParameterToJSON,
    PhiApiCloudSaveGetSaveDataPostIndexParameterToJSONTyped,
} from './PhiApiCloudSaveGetSaveDataPostIndexParameter';

/**
 * 
 * @export
 * @interface NoReadOfCompleteQRCodeData
 */
export interface NoReadOfCompleteQRCodeData {
    /**
     * 
     * @type {string}
     * @memberof NoReadOfCompleteQRCodeData
     */
    deviceID?: string;
    /**
     * 
     * @type {string}
     * @memberof NoReadOfCompleteQRCodeData
     */
    deviceCode?: string;
    /**
     * 
     * @type {PhiApiCloudSaveGetSaveDataPostIndexParameter}
     * @memberof NoReadOfCompleteQRCodeData
     */
    expiresInSeconds?: PhiApiCloudSaveGetSaveDataPostIndexParameter;
    /**
     * 
     * @type {string}
     * @memberof NoReadOfCompleteQRCodeData
     */
    url?: string;
    /**
     * 
     * @type {PhiApiCloudSaveGetSaveDataPostIndexParameter}
     * @memberof NoReadOfCompleteQRCodeData
     */
    interval?: PhiApiCloudSaveGetSaveDataPostIndexParameter;
}

/**
 * Check if a given object implements the NoReadOfCompleteQRCodeData interface.
 */
export function instanceOfNoReadOfCompleteQRCodeData(value: object): value is NoReadOfCompleteQRCodeData {
    return true;
}

export function NoReadOfCompleteQRCodeDataFromJSON(json: any): NoReadOfCompleteQRCodeData {
    return NoReadOfCompleteQRCodeDataFromJSONTyped(json, false);
}

export function NoReadOfCompleteQRCodeDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoReadOfCompleteQRCodeData {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceID': json['deviceID'] == null ? undefined : json['deviceID'],
        'deviceCode': json['deviceCode'] == null ? undefined : json['deviceCode'],
        'expiresInSeconds': json['expiresInSeconds'] == null ? undefined : PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSON(json['expiresInSeconds']),
        'url': json['url'] == null ? undefined : json['url'],
        'interval': json['interval'] == null ? undefined : PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSON(json['interval']),
    };
}

export function NoReadOfCompleteQRCodeDataToJSON(json: any): NoReadOfCompleteQRCodeData {
    return NoReadOfCompleteQRCodeDataToJSONTyped(json, false);
}

export function NoReadOfCompleteQRCodeDataToJSONTyped(value?: NoReadOfCompleteQRCodeData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deviceID': value['deviceID'],
        'deviceCode': value['deviceCode'],
        'expiresInSeconds': PhiApiCloudSaveGetSaveDataPostIndexParameterToJSON(value['expiresInSeconds']),
        'url': value['url'],
        'interval': PhiApiCloudSaveGetSaveDataPostIndexParameterToJSON(value['interval']),
    };
}

