/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokenData } from './TokenData';
import {
    TokenDataFromJSON,
    TokenDataFromJSONTyped,
    TokenDataToJSON,
    TokenDataToJSONTyped,
} from './TokenData';

/**
 * 
 * @export
 * @interface NoReadOfTapTapTokenData
 */
export interface NoReadOfTapTapTokenData {
    /**
     * 
     * @type {TokenData}
     * @memberof NoReadOfTapTapTokenData
     */
    data?: TokenData;
}

/**
 * Check if a given object implements the NoReadOfTapTapTokenData interface.
 */
export function instanceOfNoReadOfTapTapTokenData(value: object): value is NoReadOfTapTapTokenData {
    return true;
}

export function NoReadOfTapTapTokenDataFromJSON(json: any): NoReadOfTapTapTokenData {
    return NoReadOfTapTapTokenDataFromJSONTyped(json, false);
}

export function NoReadOfTapTapTokenDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoReadOfTapTapTokenData {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : TokenDataFromJSON(json['data']),
    };
}

export function NoReadOfTapTapTokenDataToJSON(json: any): NoReadOfTapTapTokenData {
    return NoReadOfTapTapTokenDataToJSONTyped(json, false);
}

export function NoReadOfTapTapTokenDataToJSONTyped(value?: NoReadOfTapTapTokenData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': TokenDataToJSON(value['data']),
    };
}

