/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PhiApiCloudSaveGetSaveDataPostIndexParameter
 */
export interface PhiApiCloudSaveGetSaveDataPostIndexParameter {
}

/**
 * Check if a given object implements the PhiApiCloudSaveGetSaveDataPostIndexParameter interface.
 */
export function instanceOfPhiApiCloudSaveGetSaveDataPostIndexParameter(value: object): value is PhiApiCloudSaveGetSaveDataPostIndexParameter {
    return true;
}

export function PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSON(json: any): PhiApiCloudSaveGetSaveDataPostIndexParameter {
    return PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSONTyped(json, false);
}

export function PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhiApiCloudSaveGetSaveDataPostIndexParameter {
    return json;
}

export function PhiApiCloudSaveGetSaveDataPostIndexParameterToJSON(json: any): PhiApiCloudSaveGetSaveDataPostIndexParameter {
    return PhiApiCloudSaveGetSaveDataPostIndexParameterToJSONTyped(json, false);
}

export function PhiApiCloudSaveGetSaveDataPostIndexParameterToJSONTyped(value?: PhiApiCloudSaveGetSaveDataPostIndexParameter | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

