/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlayerInfo
 */
export interface PlayerInfo {
    /**
     * 
     * @type {string}
     * @memberof PlayerInfo
     */
    nickName?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerInfo
     */
    userName?: string;
    /**
     * 
     * @type {Date}
     * @memberof PlayerInfo
     */
    creationTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PlayerInfo
     */
    modificationTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof PlayerInfo
     */
    objectId?: string;
}

/**
 * Check if a given object implements the PlayerInfo interface.
 */
export function instanceOfPlayerInfo(value: object): value is PlayerInfo {
    return true;
}

export function PlayerInfoFromJSON(json: any): PlayerInfo {
    return PlayerInfoFromJSONTyped(json, false);
}

export function PlayerInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'nickName': json['nickName'] == null ? undefined : json['nickName'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'creationTime': json['creationTime'] == null ? undefined : (new Date(json['creationTime'])),
        'modificationTime': json['modificationTime'] == null ? undefined : (new Date(json['modificationTime'])),
        'objectId': json['objectId'] == null ? undefined : json['objectId'],
    };
}

export function PlayerInfoToJSON(json: any): PlayerInfo {
    return PlayerInfoToJSONTyped(json, false);
}

export function PlayerInfoToJSONTyped(value?: PlayerInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nickName': value['nickName'],
        'userName': value['userName'],
        'creationTime': value['creationTime'] == null ? value['creationTime'] : value['creationTime'].toISOString(),
        'modificationTime': value['modificationTime'] == null ? value['modificationTime'] : value['modificationTime'].toISOString(),
        'objectId': value['objectId'],
    };
}

