/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChallengeRawCode } from './ChallengeRawCode';
import {
    ChallengeRawCodeFromJSON,
    ChallengeRawCodeFromJSONTyped,
    ChallengeRawCodeToJSON,
    ChallengeRawCodeToJSONTyped,
} from './ChallengeRawCode';

/**
 * 
 * @export
 * @interface PlayCountSummary
 */
export interface PlayCountSummary {
    /**
     * 
     * @type {ChallengeRawCode}
     * @memberof PlayCountSummary
     */
    clearedCount?: ChallengeRawCode;
    /**
     * 
     * @type {ChallengeRawCode}
     * @memberof PlayCountSummary
     */
    fullComboCount?: ChallengeRawCode;
    /**
     * 
     * @type {ChallengeRawCode}
     * @memberof PlayCountSummary
     */
    phiCount?: ChallengeRawCode;
}

/**
 * Check if a given object implements the PlayCountSummary interface.
 */
export function instanceOfPlayCountSummary(value: object): value is PlayCountSummary {
    return true;
}

export function PlayCountSummaryFromJSON(json: any): PlayCountSummary {
    return PlayCountSummaryFromJSONTyped(json, false);
}

export function PlayCountSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayCountSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'clearedCount': json['clearedCount'] == null ? undefined : ChallengeRawCodeFromJSON(json['clearedCount']),
        'fullComboCount': json['fullComboCount'] == null ? undefined : ChallengeRawCodeFromJSON(json['fullComboCount']),
        'phiCount': json['phiCount'] == null ? undefined : ChallengeRawCodeFromJSON(json['phiCount']),
    };
}

export function PlayCountSummaryToJSON(json: any): PlayCountSummary {
    return PlayCountSummaryToJSONTyped(json, false);
}

export function PlayCountSummaryToJSONTyped(value?: PlayCountSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clearedCount': ChallengeRawCodeToJSON(value['clearedCount']),
        'fullComboCount': ChallengeRawCodeToJSON(value['fullComboCount']),
        'phiCount': ChallengeRawCodeToJSON(value['phiCount']),
    };
}

