/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfileData
 */
export interface ProfileData {
    /**
     * 
     * @type {string}
     * @memberof ProfileData
     */
    openid?: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileData
     */
    unionid?: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileData
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileData
     */
    gender?: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileData
     */
    avatar?: string;
}

/**
 * Check if a given object implements the ProfileData interface.
 */
export function instanceOfProfileData(value: object): value is ProfileData {
    return true;
}

export function ProfileDataFromJSON(json: any): ProfileData {
    return ProfileDataFromJSONTyped(json, false);
}

export function ProfileDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileData {
    if (json == null) {
        return json;
    }
    return {
        
        'openid': json['openid'] == null ? undefined : json['openid'],
        'unionid': json['unionid'] == null ? undefined : json['unionid'],
        'name': json['name'] == null ? undefined : json['name'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
    };
}

export function ProfileDataToJSON(json: any): ProfileData {
    return ProfileDataToJSONTyped(json, false);
}

export function ProfileDataToJSONTyped(value?: ProfileData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'openid': value['openid'],
        'unionid': value['unionid'],
        'name': value['name'],
        'gender': value['gender'],
        'avatar': value['avatar'],
    };
}

