/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseOfstring
 */
export interface ResponseOfstring {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseOfstring
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof ResponseOfstring
     */
    data: string | null;
}

/**
 * Check if a given object implements the ResponseOfstring interface.
 */
export function instanceOfResponseOfstring(value: object): value is ResponseOfstring {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ResponseOfstringFromJSON(json: any): ResponseOfstring {
    return ResponseOfstringFromJSONTyped(json, false);
}

export function ResponseOfstringFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseOfstring {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'],
    };
}

export function ResponseOfstringToJSON(json: any): ResponseOfstring {
    return ResponseOfstringToJSONTyped(json, false);
}

export function ResponseOfstringToJSONTyped(value?: ResponseOfstring | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': value['data'],
    };
}

