/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TapTapProfileData } from './TapTapProfileData';
import {
    TapTapProfileDataFromJSON,
    TapTapProfileDataFromJSONTyped,
    TapTapProfileDataToJSON,
    TapTapProfileDataToJSONTyped,
} from './TapTapProfileData';

/**
 * 
 * @export
 * @interface ResponseOfTapTapProfileData
 */
export interface ResponseOfTapTapProfileData {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseOfTapTapProfileData
     */
    success: boolean;
    /**
     * 
     * @type {TapTapProfileData}
     * @memberof ResponseOfTapTapProfileData
     */
    data: TapTapProfileData | null;
}

/**
 * Check if a given object implements the ResponseOfTapTapProfileData interface.
 */
export function instanceOfResponseOfTapTapProfileData(value: object): value is ResponseOfTapTapProfileData {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ResponseOfTapTapProfileDataFromJSON(json: any): ResponseOfTapTapProfileData {
    return ResponseOfTapTapProfileDataFromJSONTyped(json, false);
}

export function ResponseOfTapTapProfileDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseOfTapTapProfileData {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': TapTapProfileDataFromJSON(json['data']),
    };
}

export function ResponseOfTapTapProfileDataToJSON(json: any): ResponseOfTapTapProfileData {
    return ResponseOfTapTapProfileDataToJSONTyped(json, false);
}

export function ResponseOfTapTapProfileDataToJSONTyped(value?: ResponseOfTapTapProfileData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': TapTapProfileDataToJSON(value['data']),
    };
}

