/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SaveData } from './SaveData';
import {
    SaveDataFromJSON,
    SaveDataFromJSONTyped,
    SaveDataToJSON,
    SaveDataToJSONTyped,
} from './SaveData';

/**
 * 
 * @export
 * @interface ResponseOfSaveData
 */
export interface ResponseOfSaveData {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseOfSaveData
     */
    success: boolean;
    /**
     * 
     * @type {SaveData}
     * @memberof ResponseOfSaveData
     */
    data: SaveData | null;
}

/**
 * Check if a given object implements the ResponseOfSaveData interface.
 */
export function instanceOfResponseOfSaveData(value: object): value is ResponseOfSaveData {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ResponseOfSaveDataFromJSON(json: any): ResponseOfSaveData {
    return ResponseOfSaveDataFromJSONTyped(json, false);
}

export function ResponseOfSaveDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseOfSaveData {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': SaveDataFromJSON(json['data']),
    };
}

export function ResponseOfSaveDataToJSON(json: any): ResponseOfSaveData {
    return ResponseOfSaveDataToJSONTyped(json, false);
}

export function ResponseOfSaveDataToJSONTyped(value?: ResponseOfSaveData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': SaveDataToJSON(value['data']),
    };
}

