/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SaveTimeIndex } from './SaveTimeIndex';
import {
    SaveTimeIndexFromJSON,
    SaveTimeIndexFromJSONTyped,
    SaveTimeIndexToJSON,
    SaveTimeIndexToJSONTyped,
} from './SaveTimeIndex';

/**
 * 
 * @export
 * @interface ResponseOfListOfSaveTimeIndex
 */
export interface ResponseOfListOfSaveTimeIndex {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseOfListOfSaveTimeIndex
     */
    success: boolean;
    /**
     * 
     * @type {Array<SaveTimeIndex>}
     * @memberof ResponseOfListOfSaveTimeIndex
     */
    data: Array<SaveTimeIndex> | null;
}

/**
 * Check if a given object implements the ResponseOfListOfSaveTimeIndex interface.
 */
export function instanceOfResponseOfListOfSaveTimeIndex(value: object): value is ResponseOfListOfSaveTimeIndex {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ResponseOfListOfSaveTimeIndexFromJSON(json: any): ResponseOfListOfSaveTimeIndex {
    return ResponseOfListOfSaveTimeIndexFromJSONTyped(json, false);
}

export function ResponseOfListOfSaveTimeIndexFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseOfListOfSaveTimeIndex {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': (json['data'] == null ? null : (json['data'] as Array<any>).map(SaveTimeIndexFromJSON)),
    };
}

export function ResponseOfListOfSaveTimeIndexToJSON(json: any): ResponseOfListOfSaveTimeIndex {
    return ResponseOfListOfSaveTimeIndexToJSONTyped(json, false);
}

export function ResponseOfListOfSaveTimeIndexToJSONTyped(value?: ResponseOfListOfSaveTimeIndex | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': (value['data'] == null ? null : (value['data'] as Array<any>).map(SaveTimeIndexToJSON)),
    };
}

