/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompleteScore } from './CompleteScore';
import {
    CompleteScoreFromJSON,
    CompleteScoreFromJSONTyped,
    CompleteScoreToJSON,
    CompleteScoreToJSONTyped,
} from './CompleteScore';

/**
 * 
 * @export
 * @interface ResponseOfListOfCompleteScore
 */
export interface ResponseOfListOfCompleteScore {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseOfListOfCompleteScore
     */
    success: boolean;
    /**
     * 
     * @type {Array<CompleteScore>}
     * @memberof ResponseOfListOfCompleteScore
     */
    data: Array<CompleteScore> | null;
}

/**
 * Check if a given object implements the ResponseOfListOfCompleteScore interface.
 */
export function instanceOfResponseOfListOfCompleteScore(value: object): value is ResponseOfListOfCompleteScore {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ResponseOfListOfCompleteScoreFromJSON(json: any): ResponseOfListOfCompleteScore {
    return ResponseOfListOfCompleteScoreFromJSONTyped(json, false);
}

export function ResponseOfListOfCompleteScoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseOfListOfCompleteScore {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': (json['data'] == null ? null : (json['data'] as Array<any>).map(CompleteScoreFromJSON)),
    };
}

export function ResponseOfListOfCompleteScoreToJSON(json: any): ResponseOfListOfCompleteScore {
    return ResponseOfListOfCompleteScoreToJSONTyped(json, false);
}

export function ResponseOfListOfCompleteScoreToJSONTyped(value?: ResponseOfListOfCompleteScore | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': (value['data'] == null ? null : (value['data'] as Array<any>).map(CompleteScoreToJSON)),
    };
}

