/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TapTapTokenData } from './TapTapTokenData';
import {
    TapTapTokenDataFromJSON,
    TapTapTokenDataFromJSONTyped,
    TapTapTokenDataToJSON,
    TapTapTokenDataToJSONTyped,
} from './TapTapTokenData';

/**
 * 
 * @export
 * @interface ResponseOfTapTapTokenData
 */
export interface ResponseOfTapTapTokenData {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseOfTapTapTokenData
     */
    success: boolean;
    /**
     * 
     * @type {TapTapTokenData}
     * @memberof ResponseOfTapTapTokenData
     */
    data: TapTapTokenData | null;
}

/**
 * Check if a given object implements the ResponseOfTapTapTokenData interface.
 */
export function instanceOfResponseOfTapTapTokenData(value: object): value is ResponseOfTapTapTokenData {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ResponseOfTapTapTokenDataFromJSON(json: any): ResponseOfTapTapTokenData {
    return ResponseOfTapTapTokenDataFromJSONTyped(json, false);
}

export function ResponseOfTapTapTokenDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseOfTapTapTokenData {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': TapTapTokenDataFromJSON(json['data']),
    };
}

export function ResponseOfTapTapTokenDataToJSON(json: any): ResponseOfTapTapTokenData {
    return ResponseOfTapTapTokenDataToJSONTyped(json, false);
}

export function ResponseOfTapTapTokenDataToJSONTyped(value?: ResponseOfTapTapTokenData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': TapTapTokenDataToJSON(value['data']),
    };
}

