/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompleteQRCodeData } from './CompleteQRCodeData';
import {
    CompleteQRCodeDataFromJSON,
    CompleteQRCodeDataFromJSONTyped,
    CompleteQRCodeDataToJSON,
    CompleteQRCodeDataToJSONTyped,
} from './CompleteQRCodeData';

/**
 * 
 * @export
 * @interface ResponseOfCompleteQRCodeData
 */
export interface ResponseOfCompleteQRCodeData {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseOfCompleteQRCodeData
     */
    success: boolean;
    /**
     * 
     * @type {CompleteQRCodeData}
     * @memberof ResponseOfCompleteQRCodeData
     */
    data: CompleteQRCodeData | null;
}

/**
 * Check if a given object implements the ResponseOfCompleteQRCodeData interface.
 */
export function instanceOfResponseOfCompleteQRCodeData(value: object): value is ResponseOfCompleteQRCodeData {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ResponseOfCompleteQRCodeDataFromJSON(json: any): ResponseOfCompleteQRCodeData {
    return ResponseOfCompleteQRCodeDataFromJSONTyped(json, false);
}

export function ResponseOfCompleteQRCodeDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseOfCompleteQRCodeData {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': CompleteQRCodeDataFromJSON(json['data']),
    };
}

export function ResponseOfCompleteQRCodeDataToJSON(json: any): ResponseOfCompleteQRCodeData {
    return ResponseOfCompleteQRCodeDataToJSONTyped(json, false);
}

export function ResponseOfCompleteQRCodeDataToJSONTyped(value?: ResponseOfCompleteQRCodeData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': CompleteQRCodeDataToJSON(value['data']),
    };
}

