/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PhiApiCloudSaveGetSaveDataPostIndexParameter } from './PhiApiCloudSaveGetSaveDataPostIndexParameter';
import {
    PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSON,
    PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSONTyped,
    PhiApiCloudSaveGetSaveDataPostIndexParameterToJSON,
    PhiApiCloudSaveGetSaveDataPostIndexParameterToJSONTyped,
} from './PhiApiCloudSaveGetSaveDataPostIndexParameter';

/**
 * 
 * @export
 * @interface SaveTimeIndex
 */
export interface SaveTimeIndex {
    /**
     * 
     * @type {PhiApiCloudSaveGetSaveDataPostIndexParameter}
     * @memberof SaveTimeIndex
     */
    index: PhiApiCloudSaveGetSaveDataPostIndexParameter;
    /**
     * 
     * @type {Date}
     * @memberof SaveTimeIndex
     */
    modificationTime: Date;
}

/**
 * Check if a given object implements the SaveTimeIndex interface.
 */
export function instanceOfSaveTimeIndex(value: object): value is SaveTimeIndex {
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('modificationTime' in value) || value['modificationTime'] === undefined) return false;
    return true;
}

export function SaveTimeIndexFromJSON(json: any): SaveTimeIndex {
    return SaveTimeIndexFromJSONTyped(json, false);
}

export function SaveTimeIndexFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveTimeIndex {
    if (json == null) {
        return json;
    }
    return {
        
        'index': PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSON(json['index']),
        'modificationTime': (new Date(json['modificationTime'])),
    };
}

export function SaveTimeIndexToJSON(json: any): SaveTimeIndex {
    return SaveTimeIndexToJSONTyped(json, false);
}

export function SaveTimeIndexToJSONTyped(value?: SaveTimeIndex | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index': PhiApiCloudSaveGetSaveDataPostIndexParameterToJSON(value['index']),
        'modificationTime': value['modificationTime'].toISOString(),
    };
}

