/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlayerInfo } from './PlayerInfo';
import {
    PlayerInfoFromJSON,
    PlayerInfoFromJSONTyped,
    PlayerInfoToJSON,
    PlayerInfoToJSONTyped,
} from './PlayerInfo';
import type { Summary } from './Summary';
import {
    SummaryFromJSON,
    SummaryFromJSONTyped,
    SummaryToJSON,
    SummaryToJSONTyped,
} from './Summary';
import type { GameSettings } from './GameSettings';
import {
    GameSettingsFromJSON,
    GameSettingsFromJSONTyped,
    GameSettingsToJSON,
    GameSettingsToJSONTyped,
} from './GameSettings';
import type { GameProgress } from './GameProgress';
import {
    GameProgressFromJSON,
    GameProgressFromJSONTyped,
    GameProgressToJSON,
    GameProgressToJSONTyped,
} from './GameProgress';
import type { GameUserInfo } from './GameUserInfo';
import {
    GameUserInfoFromJSON,
    GameUserInfoFromJSONTyped,
    GameUserInfoToJSON,
    GameUserInfoToJSONTyped,
} from './GameUserInfo';

/**
 * 
 * @export
 * @interface SaveData
 */
export interface SaveData {
    /**
     * 
     * @type {GameProgress}
     * @memberof SaveData
     */
    progress: GameProgress;
    /**
     * 
     * @type {GameSettings}
     * @memberof SaveData
     */
    settings: GameSettings;
    /**
     * 
     * @type {GameUserInfo}
     * @memberof SaveData
     */
    gameUserInfo: GameUserInfo;
    /**
     * 
     * @type {PlayerInfo}
     * @memberof SaveData
     */
    playerInfo: PlayerInfo;
    /**
     * 
     * @type {Summary}
     * @memberof SaveData
     */
    summary: Summary;
}

/**
 * Check if a given object implements the SaveData interface.
 */
export function instanceOfSaveData(value: object): value is SaveData {
    if (!('progress' in value) || value['progress'] === undefined) return false;
    if (!('settings' in value) || value['settings'] === undefined) return false;
    if (!('gameUserInfo' in value) || value['gameUserInfo'] === undefined) return false;
    if (!('playerInfo' in value) || value['playerInfo'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    return true;
}

export function SaveDataFromJSON(json: any): SaveData {
    return SaveDataFromJSONTyped(json, false);
}

export function SaveDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveData {
    if (json == null) {
        return json;
    }
    return {
        
        'progress': GameProgressFromJSON(json['progress']),
        'settings': GameSettingsFromJSON(json['settings']),
        'gameUserInfo': GameUserInfoFromJSON(json['gameUserInfo']),
        'playerInfo': PlayerInfoFromJSON(json['playerInfo']),
        'summary': SummaryFromJSON(json['summary']),
    };
}

export function SaveDataToJSON(json: any): SaveData {
    return SaveDataToJSONTyped(json, false);
}

export function SaveDataToJSONTyped(value?: SaveData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'progress': GameProgressToJSON(value['progress']),
        'settings': GameSettingsToJSON(value['settings']),
        'gameUserInfo': GameUserInfoToJSON(value['gameUserInfo']),
        'playerInfo': PlayerInfoToJSON(value['playerInfo']),
        'summary': SummaryToJSON(value['summary']),
    };
}

