/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompleteScoreChartConstant } from './CompleteScoreChartConstant';
import {
    CompleteScoreChartConstantFromJSON,
    CompleteScoreChartConstantFromJSONTyped,
    CompleteScoreChartConstantToJSON,
    CompleteScoreChartConstantToJSONTyped,
} from './CompleteScoreChartConstant';
import type { PhiApiCloudSaveGetSaveDataPostIndexParameter } from './PhiApiCloudSaveGetSaveDataPostIndexParameter';
import {
    PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSON,
    PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSONTyped,
    PhiApiCloudSaveGetSaveDataPostIndexParameterToJSON,
    PhiApiCloudSaveGetSaveDataPostIndexParameterToJSONTyped,
} from './PhiApiCloudSaveGetSaveDataPostIndexParameter';

/**
 * 
 * @export
 * @interface SongScore
 */
export interface SongScore {
    /**
     * 
     * @type {PhiApiCloudSaveGetSaveDataPostIndexParameter}
     * @memberof SongScore
     */
    score?: PhiApiCloudSaveGetSaveDataPostIndexParameter;
    /**
     * 
     * @type {CompleteScoreChartConstant}
     * @memberof SongScore
     */
    accuracy?: CompleteScoreChartConstant;
    /**
     * 
     * @type {string}
     * @memberof SongScore
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof SongScore
     */
    difficulty?: number;
    /**
     * 
     * @type {number}
     * @memberof SongScore
     */
    status?: number;
}

/**
 * Check if a given object implements the SongScore interface.
 */
export function instanceOfSongScore(value: object): value is SongScore {
    return true;
}

export function SongScoreFromJSON(json: any): SongScore {
    return SongScoreFromJSONTyped(json, false);
}

export function SongScoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): SongScore {
    if (json == null) {
        return json;
    }
    return {
        
        'score': json['score'] == null ? undefined : PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSON(json['score']),
        'accuracy': json['accuracy'] == null ? undefined : CompleteScoreChartConstantFromJSON(json['accuracy']),
        'id': json['id'] == null ? undefined : json['id'],
        'difficulty': json['difficulty'] == null ? undefined : json['difficulty'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function SongScoreToJSON(json: any): SongScore {
    return SongScoreToJSONTyped(json, false);
}

export function SongScoreToJSONTyped(value?: SongScore | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'score': PhiApiCloudSaveGetSaveDataPostIndexParameterToJSON(value['score']),
        'accuracy': CompleteScoreChartConstantToJSON(value['accuracy']),
        'id': value['id'],
        'difficulty': value['difficulty'],
        'status': value['status'],
    };
}

