/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PhiApiCloudSaveGetSaveDataPostIndexParameter } from './PhiApiCloudSaveGetSaveDataPostIndexParameter';
import {
    PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSON,
    PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSONTyped,
    PhiApiCloudSaveGetSaveDataPostIndexParameterToJSON,
    PhiApiCloudSaveGetSaveDataPostIndexParameterToJSONTyped,
} from './PhiApiCloudSaveGetSaveDataPostIndexParameter';

/**
 * 
 * @export
 * @interface StringSegment
 */
export interface StringSegment {
    /**
     * 
     * @type {string}
     * @memberof StringSegment
     */
    buffer?: string | null;
    /**
     * 
     * @type {PhiApiCloudSaveGetSaveDataPostIndexParameter}
     * @memberof StringSegment
     */
    offset?: PhiApiCloudSaveGetSaveDataPostIndexParameter;
    /**
     * 
     * @type {PhiApiCloudSaveGetSaveDataPostIndexParameter}
     * @memberof StringSegment
     */
    length?: PhiApiCloudSaveGetSaveDataPostIndexParameter;
    /**
     * 
     * @type {string}
     * @memberof StringSegment
     */
    value?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof StringSegment
     */
    hasValue?: boolean;
}

/**
 * Check if a given object implements the StringSegment interface.
 */
export function instanceOfStringSegment(value: object): value is StringSegment {
    return true;
}

export function StringSegmentFromJSON(json: any): StringSegment {
    return StringSegmentFromJSONTyped(json, false);
}

export function StringSegmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): StringSegment {
    if (json == null) {
        return json;
    }
    return {
        
        'buffer': json['buffer'] === undefined ? undefined : json['buffer'] === null ? null : json['buffer'],
        'offset': json['offset'] == null ? undefined : PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSON(json['offset']),
        'length': json['length'] == null ? undefined : PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSON(json['length']),
        'value': json['value'] === undefined ? undefined : json['value'] === null ? null : json['value'],
        'hasValue': json['hasValue'] == null ? undefined : json['hasValue'],
    };
}

export function StringSegmentToJSON(json: any): StringSegment {
    return StringSegmentToJSONTyped(json, false);
}

export function StringSegmentToJSONTyped(value?: StringSegment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'buffer': value['buffer'],
        'offset': PhiApiCloudSaveGetSaveDataPostIndexParameterToJSON(value['offset']),
        'length': PhiApiCloudSaveGetSaveDataPostIndexParameterToJSON(value['length']),
        'value': value['value'],
        'hasValue': value['hasValue'],
    };
}

