/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompleteScoreChartConstant } from './CompleteScoreChartConstant';
import {
    CompleteScoreChartConstantFromJSON,
    CompleteScoreChartConstantFromJSONTyped,
    CompleteScoreChartConstantToJSON,
    CompleteScoreChartConstantToJSONTyped,
} from './CompleteScoreChartConstant';
import type { ChallengeLevel } from './ChallengeLevel';
import {
    ChallengeLevelFromJSON,
    ChallengeLevelFromJSONTyped,
    ChallengeLevelToJSON,
    ChallengeLevelToJSONTyped,
} from './ChallengeLevel';
import type { PhiApiCloudSaveGetSaveDataPostIndexParameter } from './PhiApiCloudSaveGetSaveDataPostIndexParameter';
import {
    PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSON,
    PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSONTyped,
    PhiApiCloudSaveGetSaveDataPostIndexParameterToJSON,
    PhiApiCloudSaveGetSaveDataPostIndexParameterToJSONTyped,
} from './PhiApiCloudSaveGetSaveDataPostIndexParameter';
import type { PlayCountSummary } from './PlayCountSummary';
import {
    PlayCountSummaryFromJSON,
    PlayCountSummaryFromJSONTyped,
    PlayCountSummaryToJSON,
    PlayCountSummaryToJSONTyped,
} from './PlayCountSummary';
import type { Challenge } from './Challenge';
import {
    ChallengeFromJSON,
    ChallengeFromJSONTyped,
    ChallengeToJSON,
    ChallengeToJSONTyped,
} from './Challenge';

/**
 * 
 * @export
 * @interface Summary
 */
export interface Summary {
    /**
     * 
     * @type {ChallengeLevel}
     * @memberof Summary
     */
    saveVersion: ChallengeLevel;
    /**
     * 
     * @type {PhiApiCloudSaveGetSaveDataPostIndexParameter}
     * @memberof Summary
     */
    gameVersion: PhiApiCloudSaveGetSaveDataPostIndexParameter;
    /**
     * 
     * @type {CompleteScoreChartConstant}
     * @memberof Summary
     */
    rks: CompleteScoreChartConstant;
    /**
     * 
     * @type {Challenge}
     * @memberof Summary
     */
    challenge: Challenge;
    /**
     * 
     * @type {string}
     * @memberof Summary
     */
    avatar: string;
    /**
     * 
     * @type {PlayCountSummary}
     * @memberof Summary
     */
    ezPlayRecord?: PlayCountSummary;
    /**
     * 
     * @type {PlayCountSummary}
     * @memberof Summary
     */
    hdPlayRecord?: PlayCountSummary;
    /**
     * 
     * @type {PlayCountSummary}
     * @memberof Summary
     */
    inPlayRecord?: PlayCountSummary;
    /**
     * 
     * @type {PlayCountSummary}
     * @memberof Summary
     */
    atPlayRecord?: PlayCountSummary;
}

/**
 * Check if a given object implements the Summary interface.
 */
export function instanceOfSummary(value: object): value is Summary {
    if (!('saveVersion' in value) || value['saveVersion'] === undefined) return false;
    if (!('gameVersion' in value) || value['gameVersion'] === undefined) return false;
    if (!('rks' in value) || value['rks'] === undefined) return false;
    if (!('challenge' in value) || value['challenge'] === undefined) return false;
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    return true;
}

export function SummaryFromJSON(json: any): Summary {
    return SummaryFromJSONTyped(json, false);
}

export function SummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Summary {
    if (json == null) {
        return json;
    }
    return {
        
        'saveVersion': ChallengeLevelFromJSON(json['saveVersion']),
        'gameVersion': PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSON(json['gameVersion']),
        'rks': CompleteScoreChartConstantFromJSON(json['rks']),
        'challenge': ChallengeFromJSON(json['challenge']),
        'avatar': json['avatar'],
        'ezPlayRecord': json['ezPlayRecord'] == null ? undefined : PlayCountSummaryFromJSON(json['ezPlayRecord']),
        'hdPlayRecord': json['hdPlayRecord'] == null ? undefined : PlayCountSummaryFromJSON(json['hdPlayRecord']),
        'inPlayRecord': json['inPlayRecord'] == null ? undefined : PlayCountSummaryFromJSON(json['inPlayRecord']),
        'atPlayRecord': json['atPlayRecord'] == null ? undefined : PlayCountSummaryFromJSON(json['atPlayRecord']),
    };
}

export function SummaryToJSON(json: any): Summary {
    return SummaryToJSONTyped(json, false);
}

export function SummaryToJSONTyped(value?: Summary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'saveVersion': ChallengeLevelToJSON(value['saveVersion']),
        'gameVersion': PhiApiCloudSaveGetSaveDataPostIndexParameterToJSON(value['gameVersion']),
        'rks': CompleteScoreChartConstantToJSON(value['rks']),
        'challenge': ChallengeToJSON(value['challenge']),
        'avatar': value['avatar'],
        'ezPlayRecord': PlayCountSummaryToJSON(value['ezPlayRecord']),
        'hdPlayRecord': PlayCountSummaryToJSON(value['hdPlayRecord']),
        'inPlayRecord': PlayCountSummaryToJSON(value['inPlayRecord']),
        'atPlayRecord': PlayCountSummaryToJSON(value['atPlayRecord']),
    };
}

