/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokenData } from './TokenData';
import {
    TokenDataFromJSON,
    TokenDataFromJSONTyped,
    TokenDataToJSON,
    TokenDataToJSONTyped,
} from './TokenData';

/**
 * 
 * @export
 * @interface TapTapTokenData
 */
export interface TapTapTokenData {
    /**
     * 
     * @type {TokenData}
     * @memberof TapTapTokenData
     */
    data?: TokenData;
}

/**
 * Check if a given object implements the TapTapTokenData interface.
 */
export function instanceOfTapTapTokenData(value: object): value is TapTapTokenData {
    return true;
}

export function TapTapTokenDataFromJSON(json: any): TapTapTokenData {
    return TapTapTokenDataFromJSONTyped(json, false);
}

export function TapTapTokenDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TapTapTokenData {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : TokenDataFromJSON(json['data']),
    };
}

export function TapTapTokenDataToJSON(json: any): TapTapTokenData {
    return TapTapTokenDataToJSONTyped(json, false);
}

export function TapTapTokenDataToJSONTyped(value?: TapTapTokenData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': TokenDataToJSON(value['data']),
    };
}

