/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProfileData } from './ProfileData';
import {
    ProfileDataFromJSON,
    ProfileDataFromJSONTyped,
    ProfileDataToJSON,
    ProfileDataToJSONTyped,
} from './ProfileData';

/**
 * 
 * @export
 * @interface TapTapProfileData
 */
export interface TapTapProfileData {
    /**
     * 
     * @type {ProfileData}
     * @memberof TapTapProfileData
     */
    data?: ProfileData;
}

/**
 * Check if a given object implements the TapTapProfileData interface.
 */
export function instanceOfTapTapProfileData(value: object): value is TapTapProfileData {
    return true;
}

export function TapTapProfileDataFromJSON(json: any): TapTapProfileData {
    return TapTapProfileDataFromJSONTyped(json, false);
}

export function TapTapProfileDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TapTapProfileData {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ProfileDataFromJSON(json['data']),
    };
}

export function TapTapProfileDataToJSON(json: any): TapTapProfileData {
    return TapTapProfileDataToJSONTyped(json, false);
}

export function TapTapProfileDataToJSONTyped(value?: TapTapProfileData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ProfileDataToJSON(value['data']),
    };
}

