/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenData
 */
export interface TokenData {
    /**
     * 
     * @type {string}
     * @memberof TokenData
     */
    kid?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenData
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenData
     */
    tokenType?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenData
     */
    macKey?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenData
     */
    macAlgorithm?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenData
     */
    scope?: string;
}

/**
 * Check if a given object implements the TokenData interface.
 */
export function instanceOfTokenData(value: object): value is TokenData {
    return true;
}

export function TokenDataFromJSON(json: any): TokenData {
    return TokenDataFromJSONTyped(json, false);
}

export function TokenDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenData {
    if (json == null) {
        return json;
    }
    return {
        
        'kid': json['kid'] == null ? undefined : json['kid'],
        'accessToken': json['access_token'] == null ? undefined : json['access_token'],
        'tokenType': json['token_type'] == null ? undefined : json['token_type'],
        'macKey': json['mac_key'] == null ? undefined : json['mac_key'],
        'macAlgorithm': json['mac_algorithm'] == null ? undefined : json['mac_algorithm'],
        'scope': json['scope'] == null ? undefined : json['scope'],
    };
}

export function TokenDataToJSON(json: any): TokenData {
    return TokenDataToJSONTyped(json, false);
}

export function TokenDataToJSONTyped(value?: TokenData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kid': value['kid'],
        'access_token': value['accessToken'],
        'token_type': value['tokenType'],
        'mac_key': value['macKey'],
        'mac_algorithm': value['macAlgorithm'],
        'scope': value['scope'],
    };
}

