/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import Challenge from './model/Challenge';
import ChallengeRank from './model/ChallengeRank';
import CompleteQRCodeData from './model/CompleteQRCodeData';
import CompleteQRCodeDataNoRead from './model/CompleteQRCodeDataNoRead';
import CompleteQRCodeDataResponse from './model/CompleteQRCodeDataResponse';
import CompleteScore from './model/CompleteScore';
import Difficulty from './model/Difficulty';
import GameProgress from './model/GameProgress';
import GameProgressNodeVersion2 from './model/GameProgressNodeVersion2';
import GameProgressNodeVersion3 from './model/GameProgressNodeVersion3';
import GameProgressNodeVersion4 from './model/GameProgressNodeVersion4';
import GameRecord from './model/GameRecord';
import GameRecordResponse from './model/GameRecordResponse';
import GameSettings from './model/GameSettings';
import GameUserInfo from './model/GameUserInfo';
import Money from './model/Money';
import ProfileData from './model/ProfileData';
import SaveData from './model/SaveData';
import SaveDataResponse from './model/SaveDataResponse';
import SaveTimeIndex from './model/SaveTimeIndex';
import SaveTimeIndexListResponse from './model/SaveTimeIndexListResponse';
import ScoreStatus from './model/ScoreStatus';
import StringResponse from './model/StringResponse';
import Summary from './model/Summary';
import TapTapProfileData from './model/TapTapProfileData';
import TapTapProfileDataResponse from './model/TapTapProfileDataResponse';
import TapTapTokenData from './model/TapTapTokenData';
import TapTapTokenDataNoRead from './model/TapTapTokenDataNoRead';
import TapTapTokenDataResponse from './model/TapTapTokenDataResponse';
import TokenData from './model/TokenData';
import UserInfo from './model/UserInfo';
import CloudSaveApi from './api/CloudSaveApi';
import LocalSaveApi from './api/LocalSaveApi';
import LoginQrCodeApi from './api/LoginQrCodeApi';

/**
* Phigros_Api_a_plugin_wrapper_for_the_wrapper_of_PhigrosLibraryCSharp.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var PhigrosApi = require('index'); // See note below*.
* var xxxSvc = new PhigrosApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new PhigrosApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new PhigrosApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new PhigrosApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Challenge model constructor.
     * @property {module:model/Challenge}
     */
    Challenge,

    /**
     * The ChallengeRank model constructor.
     * @property {module:model/ChallengeRank}
     */
    ChallengeRank,

    /**
     * The CompleteQRCodeData model constructor.
     * @property {module:model/CompleteQRCodeData}
     */
    CompleteQRCodeData,

    /**
     * The CompleteQRCodeDataNoRead model constructor.
     * @property {module:model/CompleteQRCodeDataNoRead}
     */
    CompleteQRCodeDataNoRead,

    /**
     * The CompleteQRCodeDataResponse model constructor.
     * @property {module:model/CompleteQRCodeDataResponse}
     */
    CompleteQRCodeDataResponse,

    /**
     * The CompleteScore model constructor.
     * @property {module:model/CompleteScore}
     */
    CompleteScore,

    /**
     * The Difficulty model constructor.
     * @property {module:model/Difficulty}
     */
    Difficulty,

    /**
     * The GameProgress model constructor.
     * @property {module:model/GameProgress}
     */
    GameProgress,

    /**
     * The GameProgressNodeVersion2 model constructor.
     * @property {module:model/GameProgressNodeVersion2}
     */
    GameProgressNodeVersion2,

    /**
     * The GameProgressNodeVersion3 model constructor.
     * @property {module:model/GameProgressNodeVersion3}
     */
    GameProgressNodeVersion3,

    /**
     * The GameProgressNodeVersion4 model constructor.
     * @property {module:model/GameProgressNodeVersion4}
     */
    GameProgressNodeVersion4,

    /**
     * The GameRecord model constructor.
     * @property {module:model/GameRecord}
     */
    GameRecord,

    /**
     * The GameRecordResponse model constructor.
     * @property {module:model/GameRecordResponse}
     */
    GameRecordResponse,

    /**
     * The GameSettings model constructor.
     * @property {module:model/GameSettings}
     */
    GameSettings,

    /**
     * The GameUserInfo model constructor.
     * @property {module:model/GameUserInfo}
     */
    GameUserInfo,

    /**
     * The Money model constructor.
     * @property {module:model/Money}
     */
    Money,

    /**
     * The ProfileData model constructor.
     * @property {module:model/ProfileData}
     */
    ProfileData,

    /**
     * The SaveData model constructor.
     * @property {module:model/SaveData}
     */
    SaveData,

    /**
     * The SaveDataResponse model constructor.
     * @property {module:model/SaveDataResponse}
     */
    SaveDataResponse,

    /**
     * The SaveTimeIndex model constructor.
     * @property {module:model/SaveTimeIndex}
     */
    SaveTimeIndex,

    /**
     * The SaveTimeIndexListResponse model constructor.
     * @property {module:model/SaveTimeIndexListResponse}
     */
    SaveTimeIndexListResponse,

    /**
     * The ScoreStatus model constructor.
     * @property {module:model/ScoreStatus}
     */
    ScoreStatus,

    /**
     * The StringResponse model constructor.
     * @property {module:model/StringResponse}
     */
    StringResponse,

    /**
     * The Summary model constructor.
     * @property {module:model/Summary}
     */
    Summary,

    /**
     * The TapTapProfileData model constructor.
     * @property {module:model/TapTapProfileData}
     */
    TapTapProfileData,

    /**
     * The TapTapProfileDataResponse model constructor.
     * @property {module:model/TapTapProfileDataResponse}
     */
    TapTapProfileDataResponse,

    /**
     * The TapTapTokenData model constructor.
     * @property {module:model/TapTapTokenData}
     */
    TapTapTokenData,

    /**
     * The TapTapTokenDataNoRead model constructor.
     * @property {module:model/TapTapTokenDataNoRead}
     */
    TapTapTokenDataNoRead,

    /**
     * The TapTapTokenDataResponse model constructor.
     * @property {module:model/TapTapTokenDataResponse}
     */
    TapTapTokenDataResponse,

    /**
     * The TokenData model constructor.
     * @property {module:model/TokenData}
     */
    TokenData,

    /**
     * The UserInfo model constructor.
     * @property {module:model/UserInfo}
     */
    UserInfo,

    /**
    * The CloudSaveApi service constructor.
    * @property {module:api/CloudSaveApi}
    */
    CloudSaveApi,

    /**
    * The LocalSaveApi service constructor.
    * @property {module:api/LocalSaveApi}
    */
    LocalSaveApi,

    /**
    * The LoginQrCodeApi service constructor.
    * @property {module:api/LoginQrCodeApi}
    */
    LoginQrCodeApi
};
