/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type FileResult,
    FileResultFromJSON,
    FileResultToJSON,
} from '../models/FileResult';
import {
    type PhiApiCloudSaveGetSaveDataPostIndexParameter,
    PhiApiCloudSaveGetSaveDataPostIndexParameterFromJSON,
    PhiApiCloudSaveGetSaveDataPostIndexParameterToJSON,
} from '../models/PhiApiCloudSaveGetSaveDataPostIndexParameter';
import {
    type ResponseOfListOfCompleteScore,
    ResponseOfListOfCompleteScoreFromJSON,
    ResponseOfListOfCompleteScoreToJSON,
} from '../models/ResponseOfListOfCompleteScore';
import {
    type ResponseOfListOfSaveTimeIndex,
    ResponseOfListOfSaveTimeIndexFromJSON,
    ResponseOfListOfSaveTimeIndexToJSON,
} from '../models/ResponseOfListOfSaveTimeIndex';
import {
    type ResponseOfSaveData,
    ResponseOfSaveDataFromJSON,
    ResponseOfSaveDataToJSON,
} from '../models/ResponseOfSaveData';

export interface PhiApiCloudSaveGetDecryptedZipPostRequest {
    body: string;
    index?: PhiApiCloudSaveGetSaveDataPostIndexParameter;
    isInternational?: boolean;
}

export interface PhiApiCloudSaveGetRecordsPostRequest {
    body: string;
    index?: PhiApiCloudSaveGetSaveDataPostIndexParameter;
    isInternational?: boolean;
}

export interface PhiApiCloudSaveGetSaveDataPostRequest {
    body: string;
    index?: PhiApiCloudSaveGetSaveDataPostIndexParameter;
    isInternational?: boolean;
}

export interface PhiApiCloudSaveGetSaveIndexesPostRequest {
    body: string;
    isInternational?: boolean;
}

/**
 * 
 */
export class CloudSaveApi extends runtime.BaseAPI {

    /**
     * Creates request options for phiApiCloudSaveGetDecryptedZipPost without sending the request
     */
    async phiApiCloudSaveGetDecryptedZipPostRequestOpts(requestParameters: PhiApiCloudSaveGetDecryptedZipPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling phiApiCloudSaveGetDecryptedZipPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['index'] != null) {
            queryParameters['index'] = requestParameters['index'];
        }

        if (requestParameters['isInternational'] != null) {
            queryParameters['isInternational'] = requestParameters['isInternational'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/phiApi/CloudSave/GetDecryptedZip`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     */
    async phiApiCloudSaveGetDecryptedZipPostRaw(requestParameters: PhiApiCloudSaveGetDecryptedZipPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileResult>> {
        const requestOptions = await this.phiApiCloudSaveGetDecryptedZipPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileResultFromJSON(jsonValue));
    }

    /**
     */
    async phiApiCloudSaveGetDecryptedZipPost(requestParameters: PhiApiCloudSaveGetDecryptedZipPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileResult> {
        const response = await this.phiApiCloudSaveGetDecryptedZipPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for phiApiCloudSaveGetRecordsPost without sending the request
     */
    async phiApiCloudSaveGetRecordsPostRequestOpts(requestParameters: PhiApiCloudSaveGetRecordsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling phiApiCloudSaveGetRecordsPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['index'] != null) {
            queryParameters['index'] = requestParameters['index'];
        }

        if (requestParameters['isInternational'] != null) {
            queryParameters['isInternational'] = requestParameters['isInternational'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/phiApi/CloudSave/GetRecords`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     */
    async phiApiCloudSaveGetRecordsPostRaw(requestParameters: PhiApiCloudSaveGetRecordsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseOfListOfCompleteScore>> {
        const requestOptions = await this.phiApiCloudSaveGetRecordsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseOfListOfCompleteScoreFromJSON(jsonValue));
    }

    /**
     */
    async phiApiCloudSaveGetRecordsPost(requestParameters: PhiApiCloudSaveGetRecordsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseOfListOfCompleteScore> {
        const response = await this.phiApiCloudSaveGetRecordsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for phiApiCloudSaveGetSaveDataPost without sending the request
     */
    async phiApiCloudSaveGetSaveDataPostRequestOpts(requestParameters: PhiApiCloudSaveGetSaveDataPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling phiApiCloudSaveGetSaveDataPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['index'] != null) {
            queryParameters['index'] = requestParameters['index'];
        }

        if (requestParameters['isInternational'] != null) {
            queryParameters['isInternational'] = requestParameters['isInternational'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/phiApi/CloudSave/GetSaveData`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     */
    async phiApiCloudSaveGetSaveDataPostRaw(requestParameters: PhiApiCloudSaveGetSaveDataPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseOfSaveData>> {
        const requestOptions = await this.phiApiCloudSaveGetSaveDataPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseOfSaveDataFromJSON(jsonValue));
    }

    /**
     */
    async phiApiCloudSaveGetSaveDataPost(requestParameters: PhiApiCloudSaveGetSaveDataPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseOfSaveData> {
        const response = await this.phiApiCloudSaveGetSaveDataPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for phiApiCloudSaveGetSaveIndexesPost without sending the request
     */
    async phiApiCloudSaveGetSaveIndexesPostRequestOpts(requestParameters: PhiApiCloudSaveGetSaveIndexesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling phiApiCloudSaveGetSaveIndexesPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['isInternational'] != null) {
            queryParameters['isInternational'] = requestParameters['isInternational'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/phiApi/CloudSave/GetSaveIndexes`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     */
    async phiApiCloudSaveGetSaveIndexesPostRaw(requestParameters: PhiApiCloudSaveGetSaveIndexesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseOfListOfSaveTimeIndex>> {
        const requestOptions = await this.phiApiCloudSaveGetSaveIndexesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseOfListOfSaveTimeIndexFromJSON(jsonValue));
    }

    /**
     */
    async phiApiCloudSaveGetSaveIndexesPost(requestParameters: PhiApiCloudSaveGetSaveIndexesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseOfListOfSaveTimeIndex> {
        const response = await this.phiApiCloudSaveGetSaveIndexesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
