/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ResponseOfstring,
    ResponseOfstringFromJSON,
    ResponseOfstringToJSON,
} from '../models/ResponseOfstring';

export interface PhiApiLocalSaveDecryptNewPostRequest {
    body: string;
}

/**
 * 
 */
export class LocalSaveApi extends runtime.BaseAPI {

    /**
     * Creates request options for phiApiLocalSaveDecryptNewPost without sending the request
     */
    async phiApiLocalSaveDecryptNewPostRequestOpts(requestParameters: PhiApiLocalSaveDecryptNewPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling phiApiLocalSaveDecryptNewPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/phiApi/LocalSave/DecryptNew`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     */
    async phiApiLocalSaveDecryptNewPostRaw(requestParameters: PhiApiLocalSaveDecryptNewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseOfstring>> {
        const requestOptions = await this.phiApiLocalSaveDecryptNewPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseOfstringFromJSON(jsonValue));
    }

    /**
     */
    async phiApiLocalSaveDecryptNewPost(requestParameters: PhiApiLocalSaveDecryptNewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseOfstring> {
        const response = await this.phiApiLocalSaveDecryptNewPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
