/* tslint:disable */
/* eslint-disable */
/**
 * PhigrosApiRunHelper | phigrosapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type NoReadOfCompleteQRCodeData,
    NoReadOfCompleteQRCodeDataFromJSON,
    NoReadOfCompleteQRCodeDataToJSON,
} from '../models/NoReadOfCompleteQRCodeData';
import {
    type NoReadOfTapTapTokenData,
    NoReadOfTapTapTokenDataFromJSON,
    NoReadOfTapTapTokenDataToJSON,
} from '../models/NoReadOfTapTapTokenData';
import {
    type ResponseOfCompleteQRCodeData,
    ResponseOfCompleteQRCodeDataFromJSON,
    ResponseOfCompleteQRCodeDataToJSON,
} from '../models/ResponseOfCompleteQRCodeData';
import {
    type ResponseOfTapTapProfileData,
    ResponseOfTapTapProfileDataFromJSON,
    ResponseOfTapTapProfileDataToJSON,
} from '../models/ResponseOfTapTapProfileData';
import {
    type ResponseOfTapTapTokenData,
    ResponseOfTapTapTokenDataFromJSON,
    ResponseOfTapTapTokenDataToJSON,
} from '../models/ResponseOfTapTapTokenData';
import {
    type ResponseOfstring,
    ResponseOfstringFromJSON,
    ResponseOfstringToJSON,
} from '../models/ResponseOfstring';

export interface PhiApiLoginQrCodeCheckQRCodePostRequest {
    noReadOfCompleteQRCodeData: NoReadOfCompleteQRCodeData;
    useChinaEndpoint?: boolean;
}

export interface PhiApiLoginQrCodeGetNewQRCodeGetRequest {
    useChinaEndpoint?: boolean;
}

export interface PhiApiLoginQrCodeGetPhigrosTokenPostRequest {
    noReadOfTapTapTokenData: NoReadOfTapTapTokenData;
    useChinaEndpoint?: boolean;
}

export interface PhiApiLoginQrCodeGetTapTapProfilePostRequest {
    noReadOfTapTapTokenData: NoReadOfTapTapTokenData;
    useChinaEndpoint?: boolean;
}

/**
 * 
 */
export class LoginQrCodeApi extends runtime.BaseAPI {

    /**
     * Creates request options for phiApiLoginQrCodeCheckQRCodePost without sending the request
     */
    async phiApiLoginQrCodeCheckQRCodePostRequestOpts(requestParameters: PhiApiLoginQrCodeCheckQRCodePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['noReadOfCompleteQRCodeData'] == null) {
            throw new runtime.RequiredError(
                'noReadOfCompleteQRCodeData',
                'Required parameter "noReadOfCompleteQRCodeData" was null or undefined when calling phiApiLoginQrCodeCheckQRCodePost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['useChinaEndpoint'] != null) {
            queryParameters['useChinaEndpoint'] = requestParameters['useChinaEndpoint'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/phiApi/LoginQrCode/CheckQRCode`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NoReadOfCompleteQRCodeDataToJSON(requestParameters['noReadOfCompleteQRCodeData']),
        };
    }

    /**
     */
    async phiApiLoginQrCodeCheckQRCodePostRaw(requestParameters: PhiApiLoginQrCodeCheckQRCodePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseOfTapTapTokenData>> {
        const requestOptions = await this.phiApiLoginQrCodeCheckQRCodePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseOfTapTapTokenDataFromJSON(jsonValue));
    }

    /**
     */
    async phiApiLoginQrCodeCheckQRCodePost(requestParameters: PhiApiLoginQrCodeCheckQRCodePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseOfTapTapTokenData> {
        const response = await this.phiApiLoginQrCodeCheckQRCodePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for phiApiLoginQrCodeGetNewQRCodeGet without sending the request
     */
    async phiApiLoginQrCodeGetNewQRCodeGetRequestOpts(requestParameters: PhiApiLoginQrCodeGetNewQRCodeGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['useChinaEndpoint'] != null) {
            queryParameters['useChinaEndpoint'] = requestParameters['useChinaEndpoint'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/phiApi/LoginQrCode/GetNewQRCode`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async phiApiLoginQrCodeGetNewQRCodeGetRaw(requestParameters: PhiApiLoginQrCodeGetNewQRCodeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseOfCompleteQRCodeData>> {
        const requestOptions = await this.phiApiLoginQrCodeGetNewQRCodeGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseOfCompleteQRCodeDataFromJSON(jsonValue));
    }

    /**
     */
    async phiApiLoginQrCodeGetNewQRCodeGet(requestParameters: PhiApiLoginQrCodeGetNewQRCodeGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseOfCompleteQRCodeData> {
        const response = await this.phiApiLoginQrCodeGetNewQRCodeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for phiApiLoginQrCodeGetPhigrosTokenPost without sending the request
     */
    async phiApiLoginQrCodeGetPhigrosTokenPostRequestOpts(requestParameters: PhiApiLoginQrCodeGetPhigrosTokenPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['noReadOfTapTapTokenData'] == null) {
            throw new runtime.RequiredError(
                'noReadOfTapTapTokenData',
                'Required parameter "noReadOfTapTapTokenData" was null or undefined when calling phiApiLoginQrCodeGetPhigrosTokenPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['useChinaEndpoint'] != null) {
            queryParameters['useChinaEndpoint'] = requestParameters['useChinaEndpoint'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/phiApi/LoginQrCode/GetPhigrosToken`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NoReadOfTapTapTokenDataToJSON(requestParameters['noReadOfTapTapTokenData']),
        };
    }

    /**
     */
    async phiApiLoginQrCodeGetPhigrosTokenPostRaw(requestParameters: PhiApiLoginQrCodeGetPhigrosTokenPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseOfstring>> {
        const requestOptions = await this.phiApiLoginQrCodeGetPhigrosTokenPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseOfstringFromJSON(jsonValue));
    }

    /**
     */
    async phiApiLoginQrCodeGetPhigrosTokenPost(requestParameters: PhiApiLoginQrCodeGetPhigrosTokenPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseOfstring> {
        const response = await this.phiApiLoginQrCodeGetPhigrosTokenPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for phiApiLoginQrCodeGetTapTapProfilePost without sending the request
     */
    async phiApiLoginQrCodeGetTapTapProfilePostRequestOpts(requestParameters: PhiApiLoginQrCodeGetTapTapProfilePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['noReadOfTapTapTokenData'] == null) {
            throw new runtime.RequiredError(
                'noReadOfTapTapTokenData',
                'Required parameter "noReadOfTapTapTokenData" was null or undefined when calling phiApiLoginQrCodeGetTapTapProfilePost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['useChinaEndpoint'] != null) {
            queryParameters['useChinaEndpoint'] = requestParameters['useChinaEndpoint'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/phiApi/LoginQrCode/GetTapTapProfile`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NoReadOfTapTapTokenDataToJSON(requestParameters['noReadOfTapTapTokenData']),
        };
    }

    /**
     */
    async phiApiLoginQrCodeGetTapTapProfilePostRaw(requestParameters: PhiApiLoginQrCodeGetTapTapProfilePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseOfTapTapProfileData>> {
        const requestOptions = await this.phiApiLoginQrCodeGetTapTapProfilePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseOfTapTapProfileDataFromJSON(jsonValue));
    }

    /**
     */
    async phiApiLoginQrCodeGetTapTapProfilePost(requestParameters: PhiApiLoginQrCodeGetTapTapProfilePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseOfTapTapProfileData> {
        const response = await this.phiApiLoginQrCodeGetTapTapProfilePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
