/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PhigrosApi);
  }
}(this, function(expect, PhigrosApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CompleteQRCodeData', function() {
      beforeEach(function() {
        instance = new PhigrosApi.CompleteQRCodeData();
      });

      it('should create an instance of CompleteQRCodeData', function() {
        // TODO: update the code to test CompleteQRCodeData
        expect(instance).to.be.a(PhigrosApi.CompleteQRCodeData);
      });

      it('should have the property deviceId (base name: "device_id")', function() {
        // TODO: update the code to test the property deviceId
        expect(instance).to.have.property('deviceId');
        // expect(instance.deviceId).to.be(expectedValueLiteral);
      });

      it('should have the property deviceCode (base name: "device_code")', function() {
        // TODO: update the code to test the property deviceCode
        expect(instance).to.have.property('deviceCode');
        // expect(instance.deviceCode).to.be(expectedValueLiteral);
      });

      it('should have the property expiresInSeconds (base name: "expires_in_seconds")', function() {
        // TODO: update the code to test the property expiresInSeconds
        expect(instance).to.have.property('expiresInSeconds');
        // expect(instance.expiresInSeconds).to.be(expectedValueLiteral);
      });

      it('should have the property url (base name: "url")', function() {
        // TODO: update the code to test the property url
        expect(instance).to.have.property('url');
        // expect(instance.url).to.be(expectedValueLiteral);
      });

      it('should have the property interval (base name: "interval")', function() {
        // TODO: update the code to test the property interval
        expect(instance).to.have.property('interval');
        // expect(instance.interval).to.be(expectedValueLiteral);
      });

    });
  });

}));
