/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PhigrosApi);
  }
}(this, function(expect, PhigrosApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CompleteScore', function() {
      beforeEach(function() {
        instance = new PhigrosApi.CompleteScore();
      });

      it('should create an instance of CompleteScore', function() {
        // TODO: update the code to test CompleteScore
        expect(instance).to.be.a(PhigrosApi.CompleteScore);
      });

      it('should have the property score (base name: "score")', function() {
        // TODO: update the code to test the property score
        expect(instance).to.have.property('score');
        // expect(instance.score).to.be(expectedValueLiteral);
      });

      it('should have the property accuracy (base name: "accuracy")', function() {
        // TODO: update the code to test the property accuracy
        expect(instance).to.have.property('accuracy');
        // expect(instance.accuracy).to.be(expectedValueLiteral);
      });

      it('should have the property chartConstant (base name: "chart_constant")', function() {
        // TODO: update the code to test the property chartConstant
        expect(instance).to.have.property('chartConstant');
        // expect(instance.chartConstant).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property difficulty (base name: "difficulty")', function() {
        // TODO: update the code to test the property difficulty
        expect(instance).to.have.property('difficulty');
        // expect(instance.difficulty).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property rks (base name: "rks")', function() {
        // TODO: update the code to test the property rks
        expect(instance).to.have.property('rks');
        // expect(instance.rks).to.be(expectedValueLiteral);
      });

    });
  });

}));
