/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PhigrosApi);
  }
}(this, function(expect, PhigrosApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CompleteQRCodeDataNoRead', function() {
      beforeEach(function() {
        instance = new PhigrosApi.CompleteQRCodeDataNoRead();
      });

      it('should create an instance of CompleteQRCodeDataNoRead', function() {
        // TODO: update the code to test CompleteQRCodeDataNoRead
        expect(instance).to.be.a(PhigrosApi.CompleteQRCodeDataNoRead);
      });

    });
  });

}));
