/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PhigrosApi);
  }
}(this, function(expect, PhigrosApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GameRecord', function() {
      beforeEach(function() {
        instance = new PhigrosApi.GameRecord();
      });

      it('should create an instance of GameRecord', function() {
        // TODO: update the code to test GameRecord
        expect(instance).to.be.a(PhigrosApi.GameRecord);
      });

      it('should have the property version (base name: "version")', function() {
        // TODO: update the code to test the property version
        expect(instance).to.have.property('version');
        // expect(instance.version).to.be(expectedValueLiteral);
      });

      it('should have the property records (base name: "records")', function() {
        // TODO: update the code to test the property records
        expect(instance).to.have.property('records');
        // expect(instance.records).to.be(expectedValueLiteral);
      });

      it('should have the property summary (base name: "summary")', function() {
        // TODO: update the code to test the property summary
        expect(instance).to.have.property('summary');
        // expect(instance.summary).to.be(expectedValueLiteral);
      });

    });
  });

}));
