/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PhigrosApi);
  }
}(this, function(expect, PhigrosApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GameProgressNodeVersion3', function() {
      beforeEach(function() {
        instance = new PhigrosApi.GameProgressNodeVersion3();
      });

      it('should create an instance of GameProgressNodeVersion3', function() {
        // TODO: update the code to test GameProgressNodeVersion3
        expect(instance).to.be.a(PhigrosApi.GameProgressNodeVersion3);
      });

      it('should have the property chapter8UnlockBegin (base name: "chapter8_unlock_begin")', function() {
        // TODO: update the code to test the property chapter8UnlockBegin
        expect(instance).to.have.property('chapter8UnlockBegin');
        // expect(instance.chapter8UnlockBegin).to.be(expectedValueLiteral);
      });

      it('should have the property chapter8UnlockSecondPhase (base name: "chapter8_unlock_second_phase")', function() {
        // TODO: update the code to test the property chapter8UnlockSecondPhase
        expect(instance).to.have.property('chapter8UnlockSecondPhase');
        // expect(instance.chapter8UnlockSecondPhase).to.be(expectedValueLiteral);
      });

      it('should have the property chapter8Passed (base name: "chapter8_passed")', function() {
        // TODO: update the code to test the property chapter8Passed
        expect(instance).to.have.property('chapter8Passed');
        // expect(instance.chapter8Passed).to.be(expectedValueLiteral);
      });

      it('should have the property chapter8SongUnlockFlag (base name: "chapter8_song_unlock_flag")', function() {
        // TODO: update the code to test the property chapter8SongUnlockFlag
        expect(instance).to.have.property('chapter8SongUnlockFlag');
        // expect(instance.chapter8SongUnlockFlag).to.be(expectedValueLiteral);
      });

      it('should have the property node4 (base name: "node4")', function() {
        // TODO: update the code to test the property node4
        expect(instance).to.have.property('node4');
        // expect(instance.node4).to.be(expectedValueLiteral);
      });

    });
  });

}));
