/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PhigrosApi);
  }
}(this, function(expect, PhigrosApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GameSettings', function() {
      beforeEach(function() {
        instance = new PhigrosApi.GameSettings();
      });

      it('should create an instance of GameSettings', function() {
        // TODO: update the code to test GameSettings
        expect(instance).to.be.a(PhigrosApi.GameSettings);
      });

      it('should have the property version (base name: "version")', function() {
        // TODO: update the code to test the property version
        expect(instance).to.have.property('version');
        // expect(instance.version).to.be(expectedValueLiteral);
      });

      it('should have the property chordSupport (base name: "chord_support")', function() {
        // TODO: update the code to test the property chordSupport
        expect(instance).to.have.property('chordSupport');
        // expect(instance.chordSupport).to.be(expectedValueLiteral);
      });

      it('should have the property fcApIndicatorOn (base name: "fc_ap_indicator_on")', function() {
        // TODO: update the code to test the property fcApIndicatorOn
        expect(instance).to.have.property('fcApIndicatorOn');
        // expect(instance.fcApIndicatorOn).to.be(expectedValueLiteral);
      });

      it('should have the property enableHitSound (base name: "enable_hit_sound")', function() {
        // TODO: update the code to test the property enableHitSound
        expect(instance).to.have.property('enableHitSound');
        // expect(instance.enableHitSound).to.be(expectedValueLiteral);
      });

      it('should have the property lowResolutionModeOn (base name: "low_resolution_mode_on")', function() {
        // TODO: update the code to test the property lowResolutionModeOn
        expect(instance).to.have.property('lowResolutionModeOn');
        // expect(instance.lowResolutionModeOn).to.be(expectedValueLiteral);
      });

      it('should have the property deviceName (base name: "device_name")', function() {
        // TODO: update the code to test the property deviceName
        expect(instance).to.have.property('deviceName');
        // expect(instance.deviceName).to.be(expectedValueLiteral);
      });

      it('should have the property backgroundBrightness (base name: "background_brightness")', function() {
        // TODO: update the code to test the property backgroundBrightness
        expect(instance).to.have.property('backgroundBrightness');
        // expect(instance.backgroundBrightness).to.be(expectedValueLiteral);
      });

      it('should have the property musicVolume (base name: "music_volume")', function() {
        // TODO: update the code to test the property musicVolume
        expect(instance).to.have.property('musicVolume');
        // expect(instance.musicVolume).to.be(expectedValueLiteral);
      });

      it('should have the property effectVolume (base name: "effect_volume")', function() {
        // TODO: update the code to test the property effectVolume
        expect(instance).to.have.property('effectVolume');
        // expect(instance.effectVolume).to.be(expectedValueLiteral);
      });

      it('should have the property hitSoundVolume (base name: "hit_sound_volume")', function() {
        // TODO: update the code to test the property hitSoundVolume
        expect(instance).to.have.property('hitSoundVolume');
        // expect(instance.hitSoundVolume).to.be(expectedValueLiteral);
      });

      it('should have the property soundOffset (base name: "sound_offset")', function() {
        // TODO: update the code to test the property soundOffset
        expect(instance).to.have.property('soundOffset');
        // expect(instance.soundOffset).to.be(expectedValueLiteral);
      });

      it('should have the property noteScale (base name: "note_scale")', function() {
        // TODO: update the code to test the property noteScale
        expect(instance).to.have.property('noteScale');
        // expect(instance.noteScale).to.be(expectedValueLiteral);
      });

    });
  });

}));
