/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PhigrosApi);
  }
}(this, function(expect, PhigrosApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GameProgress', function() {
      beforeEach(function() {
        instance = new PhigrosApi.GameProgress();
      });

      it('should create an instance of GameProgress', function() {
        // TODO: update the code to test GameProgress
        expect(instance).to.be.a(PhigrosApi.GameProgress);
      });

      it('should have the property version (base name: "version")', function() {
        // TODO: update the code to test the property version
        expect(instance).to.have.property('version');
        // expect(instance.version).to.be(expectedValueLiteral);
      });

      it('should have the property isFirstRun (base name: "is_first_run")', function() {
        // TODO: update the code to test the property isFirstRun
        expect(instance).to.have.property('isFirstRun');
        // expect(instance.isFirstRun).to.be(expectedValueLiteral);
      });

      it('should have the property legacyChapterFinished (base name: "legacy_chapter_finished")', function() {
        // TODO: update the code to test the property legacyChapterFinished
        expect(instance).to.have.property('legacyChapterFinished');
        // expect(instance.legacyChapterFinished).to.be(expectedValueLiteral);
      });

      it('should have the property alreadyShowCollectionTip (base name: "already_show_collection_tip")', function() {
        // TODO: update the code to test the property alreadyShowCollectionTip
        expect(instance).to.have.property('alreadyShowCollectionTip');
        // expect(instance.alreadyShowCollectionTip).to.be(expectedValueLiteral);
      });

      it('should have the property alreadyShowAutoUnlockInTip (base name: "already_show_auto_unlock_in_tip")', function() {
        // TODO: update the code to test the property alreadyShowAutoUnlockInTip
        expect(instance).to.have.property('alreadyShowAutoUnlockInTip');
        // expect(instance.alreadyShowAutoUnlockInTip).to.be(expectedValueLiteral);
      });

      it('should have the property completed (base name: "completed")', function() {
        // TODO: update the code to test the property completed
        expect(instance).to.have.property('completed');
        // expect(instance.completed).to.be(expectedValueLiteral);
      });

      it('should have the property songUpdateInfo (base name: "song_update_info")', function() {
        // TODO: update the code to test the property songUpdateInfo
        expect(instance).to.have.property('songUpdateInfo');
        // expect(instance.songUpdateInfo).to.be(expectedValueLiteral);
      });

      it('should have the property challengeModeRank (base name: "challenge_mode_rank")', function() {
        // TODO: update the code to test the property challengeModeRank
        expect(instance).to.have.property('challengeModeRank');
        // expect(instance.challengeModeRank).to.be(expectedValueLiteral);
      });

      it('should have the property money (base name: "money")', function() {
        // TODO: update the code to test the property money
        expect(instance).to.have.property('money');
        // expect(instance.money).to.be(expectedValueLiteral);
      });

      it('should have the property unlockFlagOfSpasmodic (base name: "unlock_flag_of_spasmodic")', function() {
        // TODO: update the code to test the property unlockFlagOfSpasmodic
        expect(instance).to.have.property('unlockFlagOfSpasmodic');
        // expect(instance.unlockFlagOfSpasmodic).to.be(expectedValueLiteral);
      });

      it('should have the property unlockFlagOfIgallta (base name: "unlock_flag_of_igallta")', function() {
        // TODO: update the code to test the property unlockFlagOfIgallta
        expect(instance).to.have.property('unlockFlagOfIgallta');
        // expect(instance.unlockFlagOfIgallta).to.be(expectedValueLiteral);
      });

      it('should have the property unlockFlagOfRrharil (base name: "unlock_flag_of_rrharil")', function() {
        // TODO: update the code to test the property unlockFlagOfRrharil
        expect(instance).to.have.property('unlockFlagOfRrharil');
        // expect(instance.unlockFlagOfRrharil).to.be(expectedValueLiteral);
      });

      it('should have the property flagOfSongRecordKey (base name: "flag_of_song_record_key")', function() {
        // TODO: update the code to test the property flagOfSongRecordKey
        expect(instance).to.have.property('flagOfSongRecordKey');
        // expect(instance.flagOfSongRecordKey).to.be(expectedValueLiteral);
      });

      it('should have the property node2 (base name: "node2")', function() {
        // TODO: update the code to test the property node2
        expect(instance).to.have.property('node2');
        // expect(instance.node2).to.be(expectedValueLiteral);
      });

    });
  });

}));
