/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PhigrosApi);
  }
}(this, function(expect, PhigrosApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('GameUserInfo', function() {
      beforeEach(function() {
        instance = new PhigrosApi.GameUserInfo();
      });

      it('should create an instance of GameUserInfo', function() {
        // TODO: update the code to test GameUserInfo
        expect(instance).to.be.a(PhigrosApi.GameUserInfo);
      });

      it('should have the property version (base name: "version")', function() {
        // TODO: update the code to test the property version
        expect(instance).to.have.property('version');
        // expect(instance.version).to.be(expectedValueLiteral);
      });

      it('should have the property showUserId (base name: "show_user_id")', function() {
        // TODO: update the code to test the property showUserId
        expect(instance).to.have.property('showUserId');
        // expect(instance.showUserId).to.be(expectedValueLiteral);
      });

      it('should have the property intro (base name: "intro")', function() {
        // TODO: update the code to test the property intro
        expect(instance).to.have.property('intro');
        // expect(instance.intro).to.be(expectedValueLiteral);
      });

      it('should have the property avatarId (base name: "avatar_id")', function() {
        // TODO: update the code to test the property avatarId
        expect(instance).to.have.property('avatarId');
        // expect(instance.avatarId).to.be(expectedValueLiteral);
      });

      it('should have the property backgroundId (base name: "background_id")', function() {
        // TODO: update the code to test the property backgroundId
        expect(instance).to.have.property('backgroundId');
        // expect(instance.backgroundId).to.be(expectedValueLiteral);
      });

    });
  });

}));
