/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PhigrosApi);
  }
}(this, function(expect, PhigrosApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Money', function() {
      beforeEach(function() {
        instance = new PhigrosApi.Money();
      });

      it('should create an instance of Money', function() {
        // TODO: update the code to test Money
        expect(instance).to.be.a(PhigrosApi.Money);
      });

      it('should have the property kiB (base name: "ki_b")', function() {
        // TODO: update the code to test the property kiB
        expect(instance).to.have.property('kiB');
        // expect(instance.kiB).to.be(expectedValueLiteral);
      });

      it('should have the property miB (base name: "mi_b")', function() {
        // TODO: update the code to test the property miB
        expect(instance).to.have.property('miB');
        // expect(instance.miB).to.be(expectedValueLiteral);
      });

      it('should have the property giB (base name: "gi_b")', function() {
        // TODO: update the code to test the property giB
        expect(instance).to.have.property('giB');
        // expect(instance.giB).to.be(expectedValueLiteral);
      });

      it('should have the property tiB (base name: "ti_b")', function() {
        // TODO: update the code to test the property tiB
        expect(instance).to.have.property('tiB');
        // expect(instance.tiB).to.be(expectedValueLiteral);
      });

      it('should have the property piB (base name: "pi_b")', function() {
        // TODO: update the code to test the property piB
        expect(instance).to.have.property('piB');
        // expect(instance.piB).to.be(expectedValueLiteral);
      });

    });
  });

}));
