/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PhigrosApi);
  }
}(this, function(expect, PhigrosApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Summary', function() {
      beforeEach(function() {
        instance = new PhigrosApi.Summary();
      });

      it('should create an instance of Summary', function() {
        // TODO: update the code to test Summary
        expect(instance).to.be.a(PhigrosApi.Summary);
      });

      it('should have the property saveVersion (base name: "save_version")', function() {
        // TODO: update the code to test the property saveVersion
        expect(instance).to.have.property('saveVersion');
        // expect(instance.saveVersion).to.be(expectedValueLiteral);
      });

      it('should have the property gameVersion (base name: "game_version")', function() {
        // TODO: update the code to test the property gameVersion
        expect(instance).to.have.property('gameVersion');
        // expect(instance.gameVersion).to.be(expectedValueLiteral);
      });

      it('should have the property challenge (base name: "challenge")', function() {
        // TODO: update the code to test the property challenge
        expect(instance).to.have.property('challenge');
        // expect(instance.challenge).to.be(expectedValueLiteral);
      });

      it('should have the property avatar (base name: "avatar")', function() {
        // TODO: update the code to test the property avatar
        expect(instance).to.have.property('avatar');
        // expect(instance.avatar).to.be(expectedValueLiteral);
      });

      it('should have the property clears (base name: "clears")', function() {
        // TODO: update the code to test the property clears
        expect(instance).to.have.property('clears');
        // expect(instance.clears).to.be(expectedValueLiteral);
      });

    });
  });

}));
