/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PhigrosApi);
  }
}(this, function(expect, PhigrosApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TokenData', function() {
      beforeEach(function() {
        instance = new PhigrosApi.TokenData();
      });

      it('should create an instance of TokenData', function() {
        // TODO: update the code to test TokenData
        expect(instance).to.be.a(PhigrosApi.TokenData);
      });

      it('should have the property kid (base name: "kid")', function() {
        // TODO: update the code to test the property kid
        expect(instance).to.have.property('kid');
        // expect(instance.kid).to.be(expectedValueLiteral);
      });

      it('should have the property accessToken (base name: "access_token")', function() {
        // TODO: update the code to test the property accessToken
        expect(instance).to.have.property('accessToken');
        // expect(instance.accessToken).to.be(expectedValueLiteral);
      });

      it('should have the property tokenType (base name: "token_type")', function() {
        // TODO: update the code to test the property tokenType
        expect(instance).to.have.property('tokenType');
        // expect(instance.tokenType).to.be(expectedValueLiteral);
      });

      it('should have the property macKey (base name: "mac_key")', function() {
        // TODO: update the code to test the property macKey
        expect(instance).to.have.property('macKey');
        // expect(instance.macKey).to.be(expectedValueLiteral);
      });

      it('should have the property macAlgorithm (base name: "mac_algorithm")', function() {
        // TODO: update the code to test the property macAlgorithm
        expect(instance).to.have.property('macAlgorithm');
        // expect(instance.macAlgorithm).to.be(expectedValueLiteral);
      });

      it('should have the property scope (base name: "scope")', function() {
        // TODO: update the code to test the property scope
        expect(instance).to.have.property('scope');
        // expect(instance.scope).to.be(expectedValueLiteral);
      });

    });
  });

}));
