/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PhigrosApi);
  }
}(this, function(expect, PhigrosApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('UserInfo', function() {
      beforeEach(function() {
        instance = new PhigrosApi.UserInfo();
      });

      it('should create an instance of UserInfo', function() {
        // TODO: update the code to test UserInfo
        expect(instance).to.be.a(PhigrosApi.UserInfo);
      });

      it('should have the property nickName (base name: "nick_name")', function() {
        // TODO: update the code to test the property nickName
        expect(instance).to.have.property('nickName');
        // expect(instance.nickName).to.be(expectedValueLiteral);
      });

      it('should have the property userName (base name: "user_name")', function() {
        // TODO: update the code to test the property userName
        expect(instance).to.have.property('userName');
        // expect(instance.userName).to.be(expectedValueLiteral);
      });

      it('should have the property creationTime (base name: "creation_time")', function() {
        // TODO: update the code to test the property creationTime
        expect(instance).to.have.property('creationTime');
        // expect(instance.creationTime).to.be(expectedValueLiteral);
      });

      it('should have the property modificationTime (base name: "modification_time")', function() {
        // TODO: update the code to test the property modificationTime
        expect(instance).to.have.property('modificationTime');
        // expect(instance.modificationTime).to.be(expectedValueLiteral);
      });

    });
  });

}));
