/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import GameRecordResponse from '../model/GameRecordResponse';
import SaveDataResponse from '../model/SaveDataResponse';
import SaveTimeIndexListResponse from '../model/SaveTimeIndexListResponse';

/**
* CloudSave service.
* @module api/CloudSaveApi
* @version v1
*/
export default class CloudSaveApi {

    /**
    * Constructs a new CloudSaveApi. 
    * @alias module:api/CloudSaveApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the phiApiCloudSaveGetDecryptedZipPost operation.
     * @callback moduleapi/CloudSaveApi~phiApiCloudSaveGetDecryptedZipPostCallback
     * @param {String} error Error message, if any.
     * @param {'Blob'{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.body 
     * @param {Number} opts.index 
     * @param {Boolean} opts.isInternational 
     * @param {module:api/CloudSaveApi~phiApiCloudSaveGetDecryptedZipPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    phiApiCloudSaveGetDecryptedZipPost(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        'index': opts['index'],'isInternational': opts['isInternational']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['text/plain'];
      let accepts = ['application/zip'];
      let returnType = 'Blob';

      return this.apiClient.callApi(
        '/phiApi/CloudSave/GetDecryptedZip', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the phiApiCloudSaveGetRecordsPost operation.
     * @callback moduleapi/CloudSaveApi~phiApiCloudSaveGetRecordsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GameRecordResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.body 
     * @param {Number} opts.index 
     * @param {Boolean} opts.isInternational 
     * @param {module:api/CloudSaveApi~phiApiCloudSaveGetRecordsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    phiApiCloudSaveGetRecordsPost(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        'index': opts['index'],'isInternational': opts['isInternational']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['text/plain'];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = GameRecordResponse;

      return this.apiClient.callApi(
        '/phiApi/CloudSave/GetRecords', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the phiApiCloudSaveGetSaveDataPost operation.
     * @callback moduleapi/CloudSaveApi~phiApiCloudSaveGetSaveDataPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SaveDataResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.body 
     * @param {Number} opts.index 
     * @param {Boolean} opts.isInternational 
     * @param {module:api/CloudSaveApi~phiApiCloudSaveGetSaveDataPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    phiApiCloudSaveGetSaveDataPost(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        'index': opts['index'],'isInternational': opts['isInternational']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['text/plain'];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = SaveDataResponse;

      return this.apiClient.callApi(
        '/phiApi/CloudSave/GetSaveData', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the phiApiCloudSaveGetSaveIndexesPost operation.
     * @callback moduleapi/CloudSaveApi~phiApiCloudSaveGetSaveIndexesPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SaveTimeIndexListResponse{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} opts.body 
     * @param {Boolean} opts.isInternational 
     * @param {module:api/CloudSaveApi~phiApiCloudSaveGetSaveIndexesPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    phiApiCloudSaveGetSaveIndexesPost(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        'isInternational': opts['isInternational']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['text/plain'];
      let accepts = ['text/plain', 'application/json', 'text/json'];
      let returnType = SaveTimeIndexListResponse;

      return this.apiClient.callApi(
        '/phiApi/CloudSave/GetSaveIndexes', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}