/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CompleteQRCodeDataNoRead model module.
 * @module model/CompleteQRCodeDataNoRead
 * @version v1
 */
export default class CompleteQRCodeDataNoRead {
  /**
   * Constructs a new <code>CompleteQRCodeDataNoRead</code>.
   * @alias module:model/CompleteQRCodeDataNoRead
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CompleteQRCodeDataNoRead</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CompleteQRCodeDataNoRead} obj Optional instance to populate.
   * @return {module:model/CompleteQRCodeDataNoRead} The populated <code>CompleteQRCodeDataNoRead</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CompleteQRCodeDataNoRead();
    }
    return obj;
  }
}
