/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The CompleteQRCodeData model module.
 * @module model/CompleteQRCodeData
 * @version v1
 */
export default class CompleteQRCodeData {
  /**
   * Constructs a new <code>CompleteQRCodeData</code>.
   * @alias module:model/CompleteQRCodeData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CompleteQRCodeData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CompleteQRCodeData} obj Optional instance to populate.
   * @return {module:model/CompleteQRCodeData} The populated <code>CompleteQRCodeData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CompleteQRCodeData();
      if (data.hasOwnProperty('deviceID'))
        obj.deviceID = ApiClient.convertToType(data['deviceID'], 'String');
      if (data.hasOwnProperty('deviceCode'))
        obj.deviceCode = ApiClient.convertToType(data['deviceCode'], 'String');
      if (data.hasOwnProperty('expiresInSeconds'))
        obj.expiresInSeconds = ApiClient.convertToType(data['expiresInSeconds'], 'Number');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('interval'))
        obj.interval = ApiClient.convertToType(data['interval'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} deviceID
 */
CompleteQRCodeData.prototype.deviceID = undefined;

/**
 * @member {String} deviceCode
 */
CompleteQRCodeData.prototype.deviceCode = undefined;

/**
 * @member {Number} expiresInSeconds
 */
CompleteQRCodeData.prototype.expiresInSeconds = undefined;

/**
 * @member {String} url
 */
CompleteQRCodeData.prototype.url = undefined;

/**
 * @member {Number} interval
 */
CompleteQRCodeData.prototype.interval = undefined;

