/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import CompleteQRCodeData from './CompleteQRCodeData';

/**
 * The CompleteQRCodeDataResponse model module.
 * @module model/CompleteQRCodeDataResponse
 * @version v1
 */
export default class CompleteQRCodeDataResponse {
  /**
   * Constructs a new <code>CompleteQRCodeDataResponse</code>.
   * @alias module:model/CompleteQRCodeDataResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CompleteQRCodeDataResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CompleteQRCodeDataResponse} obj Optional instance to populate.
   * @return {module:model/CompleteQRCodeDataResponse} The populated <code>CompleteQRCodeDataResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CompleteQRCodeDataResponse();
      if (data.hasOwnProperty('success'))
        obj.success = ApiClient.convertToType(data['success'], 'Boolean');
      if (data.hasOwnProperty('data'))
        obj.data = CompleteQRCodeData.constructFromObject(data['data']);
    }
    return obj;
  }
}

/**
 * @member {Boolean} success
 */
CompleteQRCodeDataResponse.prototype.success = undefined;

/**
 * @member {module:model/CompleteQRCodeData} data
 */
CompleteQRCodeDataResponse.prototype.data = undefined;

