/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import GameProgressNodeVersion4 from './GameProgressNodeVersion4';

/**
 * The GameProgressNodeVersion3 model module.
 * @module model/GameProgressNodeVersion3
 * @version v1
 */
export default class GameProgressNodeVersion3 {
  /**
   * Constructs a new <code>GameProgressNodeVersion3</code>.
   * @alias module:model/GameProgressNodeVersion3
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GameProgressNodeVersion3</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GameProgressNodeVersion3} obj Optional instance to populate.
   * @return {module:model/GameProgressNodeVersion3} The populated <code>GameProgressNodeVersion3</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GameProgressNodeVersion3();
      if (data.hasOwnProperty('chapter8_unlock_begin'))
        obj.chapter8UnlockBegin = ApiClient.convertToType(data['chapter8_unlock_begin'], 'Boolean');
      if (data.hasOwnProperty('chapter8_unlock_second_phase'))
        obj.chapter8UnlockSecondPhase = ApiClient.convertToType(data['chapter8_unlock_second_phase'], 'Boolean');
      if (data.hasOwnProperty('chapter8_passed'))
        obj.chapter8Passed = ApiClient.convertToType(data['chapter8_passed'], 'Boolean');
      if (data.hasOwnProperty('chapter8_song_unlock_flag'))
        obj.chapter8SongUnlockFlag = ApiClient.convertToType(data['chapter8_song_unlock_flag'], 'Number');
      if (data.hasOwnProperty('node4'))
        obj.node4 = GameProgressNodeVersion4.constructFromObject(data['node4']);
    }
    return obj;
  }
}

/**
 * @member {Boolean} chapter8UnlockBegin
 */
GameProgressNodeVersion3.prototype.chapter8UnlockBegin = undefined;

/**
 * @member {Boolean} chapter8UnlockSecondPhase
 */
GameProgressNodeVersion3.prototype.chapter8UnlockSecondPhase = undefined;

/**
 * @member {Boolean} chapter8Passed
 */
GameProgressNodeVersion3.prototype.chapter8Passed = undefined;

/**
 * @member {Number} chapter8SongUnlockFlag
 */
GameProgressNodeVersion3.prototype.chapter8SongUnlockFlag = undefined;

/**
 * @member {module:model/GameProgressNodeVersion4} node4
 */
GameProgressNodeVersion3.prototype.node4 = undefined;

