/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The GameSettings model module.
 * @module model/GameSettings
 * @version v1
 */
export default class GameSettings {
  /**
   * Constructs a new <code>GameSettings</code>.
   * @alias module:model/GameSettings
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GameSettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GameSettings} obj Optional instance to populate.
   * @return {module:model/GameSettings} The populated <code>GameSettings</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GameSettings();
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'Number');
      if (data.hasOwnProperty('chordSupport'))
        obj.chordSupport = ApiClient.convertToType(data['chordSupport'], 'Boolean');
      if (data.hasOwnProperty('fcApIndicatorOn'))
        obj.fcApIndicatorOn = ApiClient.convertToType(data['fcApIndicatorOn'], 'Boolean');
      if (data.hasOwnProperty('enableHitSound'))
        obj.enableHitSound = ApiClient.convertToType(data['enableHitSound'], 'Boolean');
      if (data.hasOwnProperty('lowResolutionModeOn'))
        obj.lowResolutionModeOn = ApiClient.convertToType(data['lowResolutionModeOn'], 'Boolean');
      if (data.hasOwnProperty('deviceName'))
        obj.deviceName = ApiClient.convertToType(data['deviceName'], 'String');
      if (data.hasOwnProperty('backgroundBrightness'))
        obj.backgroundBrightness = ApiClient.convertToType(data['backgroundBrightness'], 'Number');
      if (data.hasOwnProperty('musicVolume'))
        obj.musicVolume = ApiClient.convertToType(data['musicVolume'], 'Number');
      if (data.hasOwnProperty('effectVolume'))
        obj.effectVolume = ApiClient.convertToType(data['effectVolume'], 'Number');
      if (data.hasOwnProperty('hitSoundVolume'))
        obj.hitSoundVolume = ApiClient.convertToType(data['hitSoundVolume'], 'Number');
      if (data.hasOwnProperty('soundOffset'))
        obj.soundOffset = ApiClient.convertToType(data['soundOffset'], 'Number');
      if (data.hasOwnProperty('noteScale'))
        obj.noteScale = ApiClient.convertToType(data['noteScale'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} version
 */
GameSettings.prototype.version = undefined;

/**
 * @member {Boolean} chordSupport
 */
GameSettings.prototype.chordSupport = undefined;

/**
 * @member {Boolean} fcApIndicatorOn
 */
GameSettings.prototype.fcApIndicatorOn = undefined;

/**
 * @member {Boolean} enableHitSound
 */
GameSettings.prototype.enableHitSound = undefined;

/**
 * @member {Boolean} lowResolutionModeOn
 */
GameSettings.prototype.lowResolutionModeOn = undefined;

/**
 * @member {String} deviceName
 */
GameSettings.prototype.deviceName = undefined;

/**
 * @member {Number} backgroundBrightness
 */
GameSettings.prototype.backgroundBrightness = undefined;

/**
 * @member {Number} musicVolume
 */
GameSettings.prototype.musicVolume = undefined;

/**
 * @member {Number} effectVolume
 */
GameSettings.prototype.effectVolume = undefined;

/**
 * @member {Number} hitSoundVolume
 */
GameSettings.prototype.hitSoundVolume = undefined;

/**
 * @member {Number} soundOffset
 */
GameSettings.prototype.soundOffset = undefined;

/**
 * @member {Number} noteScale
 */
GameSettings.prototype.noteScale = undefined;

