/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import GameProgressNodeVersion3 from './GameProgressNodeVersion3';

/**
 * The GameProgressNodeVersion2 model module.
 * @module model/GameProgressNodeVersion2
 * @version v1
 */
export default class GameProgressNodeVersion2 {
  /**
   * Constructs a new <code>GameProgressNodeVersion2</code>.
   * @alias module:model/GameProgressNodeVersion2
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GameProgressNodeVersion2</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GameProgressNodeVersion2} obj Optional instance to populate.
   * @return {module:model/GameProgressNodeVersion2} The populated <code>GameProgressNodeVersion2</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GameProgressNodeVersion2();
      if (data.hasOwnProperty('random_version_unlocked'))
        obj.randomVersionUnlocked = ApiClient.convertToType(data['random_version_unlocked'], 'Number');
      if (data.hasOwnProperty('node3'))
        obj.node3 = GameProgressNodeVersion3.constructFromObject(data['node3']);
    }
    return obj;
  }
}

/**
 * @member {Number} randomVersionUnlocked
 */
GameProgressNodeVersion2.prototype.randomVersionUnlocked = undefined;

/**
 * @member {module:model/GameProgressNodeVersion3} node3
 */
GameProgressNodeVersion2.prototype.node3 = undefined;

