/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The GameProgressNodeVersion4 model module.
 * @module model/GameProgressNodeVersion4
 * @version v1
 */
export default class GameProgressNodeVersion4 {
  /**
   * Constructs a new <code>GameProgressNodeVersion4</code>.
   * @alias module:model/GameProgressNodeVersion4
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GameProgressNodeVersion4</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GameProgressNodeVersion4} obj Optional instance to populate.
   * @return {module:model/GameProgressNodeVersion4} The populated <code>GameProgressNodeVersion4</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GameProgressNodeVersion4();
      if (data.hasOwnProperty('flag_of_song_record_key_takumi'))
        obj.flagOfSongRecordKeyTakumi = ApiClient.convertToType(data['flag_of_song_record_key_takumi'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} flagOfSongRecordKeyTakumi
 */
GameProgressNodeVersion4.prototype.flagOfSongRecordKeyTakumi = undefined;

