/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import CompleteScore from './CompleteScore';

/**
 * The GameRecord model module.
 * @module model/GameRecord
 * @version v1
 */
export default class GameRecord {
  /**
   * Constructs a new <code>GameRecord</code>.
   * @alias module:model/GameRecord
   * @class
   * @param version {Number} 
   * @param records {Array.<module:model/CompleteScore>} 
   */
  constructor(version, records) {
    this.version = version;
    this.records = records;
  }

  /**
   * Constructs a <code>GameRecord</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GameRecord} obj Optional instance to populate.
   * @return {module:model/GameRecord} The populated <code>GameRecord</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GameRecord();
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'Number');
      if (data.hasOwnProperty('records'))
        obj.records = ApiClient.convertToType(data['records'], [CompleteScore]);
      if (data.hasOwnProperty('summary'))
        obj.summary = ApiClient.convertToType(data['summary'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} version
 */
GameRecord.prototype.version = undefined;

/**
 * @member {Array.<module:model/CompleteScore>} records
 */
GameRecord.prototype.records = undefined;

/**
 * @member {String} summary
 */
GameRecord.prototype.summary = undefined;

