/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The GameUserInfo model module.
 * @module model/GameUserInfo
 * @version v1
 */
export default class GameUserInfo {
  /**
   * Constructs a new <code>GameUserInfo</code>.
   * @alias module:model/GameUserInfo
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GameUserInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GameUserInfo} obj Optional instance to populate.
   * @return {module:model/GameUserInfo} The populated <code>GameUserInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GameUserInfo();
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'Number');
      if (data.hasOwnProperty('showUserId'))
        obj.showUserId = ApiClient.convertToType(data['showUserId'], 'Boolean');
      if (data.hasOwnProperty('intro'))
        obj.intro = ApiClient.convertToType(data['intro'], 'String');
      if (data.hasOwnProperty('avatarId'))
        obj.avatarId = ApiClient.convertToType(data['avatarId'], 'String');
      if (data.hasOwnProperty('backgroundId'))
        obj.backgroundId = ApiClient.convertToType(data['backgroundId'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} version
 */
GameUserInfo.prototype.version = undefined;

/**
 * @member {Boolean} showUserId
 */
GameUserInfo.prototype.showUserId = undefined;

/**
 * @member {String} intro
 */
GameUserInfo.prototype.intro = undefined;

/**
 * @member {String} avatarId
 */
GameUserInfo.prototype.avatarId = undefined;

/**
 * @member {String} backgroundId
 */
GameUserInfo.prototype.backgroundId = undefined;

