/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Challenge from './Challenge';
import GameProgressNodeVersion2 from './GameProgressNodeVersion2';
import Money from './Money';

/**
 * The GameProgress model module.
 * @module model/GameProgress
 * @version v1
 */
export default class GameProgress {
  /**
   * Constructs a new <code>GameProgress</code>.
   * @alias module:model/GameProgress
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GameProgress</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GameProgress} obj Optional instance to populate.
   * @return {module:model/GameProgress} The populated <code>GameProgress</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GameProgress();
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'Number');
      if (data.hasOwnProperty('is_first_run'))
        obj.isFirstRun = ApiClient.convertToType(data['is_first_run'], 'Boolean');
      if (data.hasOwnProperty('legacy_chapter_finished'))
        obj.legacyChapterFinished = ApiClient.convertToType(data['legacy_chapter_finished'], 'Boolean');
      if (data.hasOwnProperty('already_show_collection_tip'))
        obj.alreadyShowCollectionTip = ApiClient.convertToType(data['already_show_collection_tip'], 'Boolean');
      if (data.hasOwnProperty('already_show_auto_unlock_in_tip'))
        obj.alreadyShowAutoUnlockInTip = ApiClient.convertToType(data['already_show_auto_unlock_in_tip'], 'Boolean');
      if (data.hasOwnProperty('completed'))
        obj.completed = ApiClient.convertToType(data['completed'], 'String');
      if (data.hasOwnProperty('song_update_info'))
        obj.songUpdateInfo = ApiClient.convertToType(data['song_update_info'], 'Number');
      if (data.hasOwnProperty('challenge_mode_rank'))
        obj.challengeModeRank = Challenge.constructFromObject(data['challenge_mode_rank']);
      if (data.hasOwnProperty('money'))
        obj.money = Money.constructFromObject(data['money']);
      if (data.hasOwnProperty('unlock_flag_of_spasmodic'))
        obj.unlockFlagOfSpasmodic = ApiClient.convertToType(data['unlock_flag_of_spasmodic'], 'Number');
      if (data.hasOwnProperty('unlock_flag_of_igallta'))
        obj.unlockFlagOfIgallta = ApiClient.convertToType(data['unlock_flag_of_igallta'], 'Number');
      if (data.hasOwnProperty('unlock_flag_of_rrharil'))
        obj.unlockFlagOfRrharil = ApiClient.convertToType(data['unlock_flag_of_rrharil'], 'Number');
      if (data.hasOwnProperty('flag_of_song_record_key'))
        obj.flagOfSongRecordKey = ApiClient.convertToType(data['flag_of_song_record_key'], 'Number');
      if (data.hasOwnProperty('node2'))
        obj.node2 = GameProgressNodeVersion2.constructFromObject(data['node2']);
    }
    return obj;
  }
}

/**
 * @member {Number} version
 */
GameProgress.prototype.version = undefined;

/**
 * @member {Boolean} isFirstRun
 */
GameProgress.prototype.isFirstRun = undefined;

/**
 * @member {Boolean} legacyChapterFinished
 */
GameProgress.prototype.legacyChapterFinished = undefined;

/**
 * @member {Boolean} alreadyShowCollectionTip
 */
GameProgress.prototype.alreadyShowCollectionTip = undefined;

/**
 * @member {Boolean} alreadyShowAutoUnlockInTip
 */
GameProgress.prototype.alreadyShowAutoUnlockInTip = undefined;

/**
 * @member {String} completed
 */
GameProgress.prototype.completed = undefined;

/**
 * @member {Number} songUpdateInfo
 */
GameProgress.prototype.songUpdateInfo = undefined;

/**
 * @member {module:model/Challenge} challengeModeRank
 */
GameProgress.prototype.challengeModeRank = undefined;

/**
 * @member {module:model/Money} money
 */
GameProgress.prototype.money = undefined;

/**
 * @member {Number} unlockFlagOfSpasmodic
 */
GameProgress.prototype.unlockFlagOfSpasmodic = undefined;

/**
 * @member {Number} unlockFlagOfIgallta
 */
GameProgress.prototype.unlockFlagOfIgallta = undefined;

/**
 * @member {Number} unlockFlagOfRrharil
 */
GameProgress.prototype.unlockFlagOfRrharil = undefined;

/**
 * @member {Number} flagOfSongRecordKey
 */
GameProgress.prototype.flagOfSongRecordKey = undefined;

/**
 * @member {module:model/GameProgressNodeVersion2} node2
 */
GameProgress.prototype.node2 = undefined;

