/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Challenge from './Challenge';
import GameProgressNodeVersion2 from './GameProgressNodeVersion2';
import Money from './Money';

/**
 * The GameProgress model module.
 * @module model/GameProgress
 * @version v1
 */
export default class GameProgress {
  /**
   * Constructs a new <code>GameProgress</code>.
   * @alias module:model/GameProgress
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GameProgress</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GameProgress} obj Optional instance to populate.
   * @return {module:model/GameProgress} The populated <code>GameProgress</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GameProgress();
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'Number');
      if (data.hasOwnProperty('isFirstRun'))
        obj.isFirstRun = ApiClient.convertToType(data['isFirstRun'], 'Boolean');
      if (data.hasOwnProperty('legacyChapterFinished'))
        obj.legacyChapterFinished = ApiClient.convertToType(data['legacyChapterFinished'], 'Boolean');
      if (data.hasOwnProperty('alreadyShowCollectionTip'))
        obj.alreadyShowCollectionTip = ApiClient.convertToType(data['alreadyShowCollectionTip'], 'Boolean');
      if (data.hasOwnProperty('alreadyShowAutoUnlockINTip'))
        obj.alreadyShowAutoUnlockINTip = ApiClient.convertToType(data['alreadyShowAutoUnlockINTip'], 'Boolean');
      if (data.hasOwnProperty('completed'))
        obj.completed = ApiClient.convertToType(data['completed'], 'String');
      if (data.hasOwnProperty('songUpdateInfo'))
        obj.songUpdateInfo = ApiClient.convertToType(data['songUpdateInfo'], 'Number');
      if (data.hasOwnProperty('challengeModeRank'))
        obj.challengeModeRank = Challenge.constructFromObject(data['challengeModeRank']);
      if (data.hasOwnProperty('money'))
        obj.money = Money.constructFromObject(data['money']);
      if (data.hasOwnProperty('unlockFlagOfSpasmodic'))
        obj.unlockFlagOfSpasmodic = ApiClient.convertToType(data['unlockFlagOfSpasmodic'], 'Number');
      if (data.hasOwnProperty('unlockFlagOfIgallta'))
        obj.unlockFlagOfIgallta = ApiClient.convertToType(data['unlockFlagOfIgallta'], 'Number');
      if (data.hasOwnProperty('unlockFlagOfRrharil'))
        obj.unlockFlagOfRrharil = ApiClient.convertToType(data['unlockFlagOfRrharil'], 'Number');
      if (data.hasOwnProperty('flagOfSongRecordKey'))
        obj.flagOfSongRecordKey = ApiClient.convertToType(data['flagOfSongRecordKey'], 'Number');
      if (data.hasOwnProperty('node2'))
        obj.node2 = GameProgressNodeVersion2.constructFromObject(data['node2']);
    }
    return obj;
  }
}

/**
 * @member {Number} version
 */
GameProgress.prototype.version = undefined;

/**
 * @member {Boolean} isFirstRun
 */
GameProgress.prototype.isFirstRun = undefined;

/**
 * @member {Boolean} legacyChapterFinished
 */
GameProgress.prototype.legacyChapterFinished = undefined;

/**
 * @member {Boolean} alreadyShowCollectionTip
 */
GameProgress.prototype.alreadyShowCollectionTip = undefined;

/**
 * @member {Boolean} alreadyShowAutoUnlockINTip
 */
GameProgress.prototype.alreadyShowAutoUnlockINTip = undefined;

/**
 * @member {String} completed
 */
GameProgress.prototype.completed = undefined;

/**
 * @member {Number} songUpdateInfo
 */
GameProgress.prototype.songUpdateInfo = undefined;

/**
 * @member {module:model/Challenge} challengeModeRank
 */
GameProgress.prototype.challengeModeRank = undefined;

/**
 * @member {module:model/Money} money
 */
GameProgress.prototype.money = undefined;

/**
 * @member {Number} unlockFlagOfSpasmodic
 */
GameProgress.prototype.unlockFlagOfSpasmodic = undefined;

/**
 * @member {Number} unlockFlagOfIgallta
 */
GameProgress.prototype.unlockFlagOfIgallta = undefined;

/**
 * @member {Number} unlockFlagOfRrharil
 */
GameProgress.prototype.unlockFlagOfRrharil = undefined;

/**
 * @member {Number} flagOfSongRecordKey
 */
GameProgress.prototype.flagOfSongRecordKey = undefined;

/**
 * @member {module:model/GameProgressNodeVersion2} node2
 */
GameProgress.prototype.node2 = undefined;

