/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The Money model module.
 * @module model/Money
 * @version v1
 */
export default class Money {
  /**
   * Constructs a new <code>Money</code>.
   * @alias module:model/Money
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Money</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Money} obj Optional instance to populate.
   * @return {module:model/Money} The populated <code>Money</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Money();
      if (data.hasOwnProperty('kiB'))
        obj.kiB = ApiClient.convertToType(data['kiB'], 'Number');
      if (data.hasOwnProperty('miB'))
        obj.miB = ApiClient.convertToType(data['miB'], 'Number');
      if (data.hasOwnProperty('giB'))
        obj.giB = ApiClient.convertToType(data['giB'], 'Number');
      if (data.hasOwnProperty('tiB'))
        obj.tiB = ApiClient.convertToType(data['tiB'], 'Number');
      if (data.hasOwnProperty('piB'))
        obj.piB = ApiClient.convertToType(data['piB'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} kiB
 */
Money.prototype.kiB = undefined;

/**
 * @member {Number} miB
 */
Money.prototype.miB = undefined;

/**
 * @member {Number} giB
 */
Money.prototype.giB = undefined;

/**
 * @member {Number} tiB
 */
Money.prototype.tiB = undefined;

/**
 * @member {Number} piB
 */
Money.prototype.piB = undefined;

