/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ProfileData model module.
 * @module model/ProfileData
 * @version v1
 */
export default class ProfileData {
  /**
   * Constructs a new <code>ProfileData</code>.
   * @alias module:model/ProfileData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ProfileData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProfileData} obj Optional instance to populate.
   * @return {module:model/ProfileData} The populated <code>ProfileData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProfileData();
      if (data.hasOwnProperty('openid'))
        obj.openid = ApiClient.convertToType(data['openid'], 'String');
      if (data.hasOwnProperty('unionid'))
        obj.unionid = ApiClient.convertToType(data['unionid'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('gender'))
        obj.gender = ApiClient.convertToType(data['gender'], 'String');
      if (data.hasOwnProperty('avatar'))
        obj.avatar = ApiClient.convertToType(data['avatar'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} openid
 */
ProfileData.prototype.openid = undefined;

/**
 * @member {String} unionid
 */
ProfileData.prototype.unionid = undefined;

/**
 * @member {String} name
 */
ProfileData.prototype.name = undefined;

/**
 * @member {String} gender
 */
ProfileData.prototype.gender = undefined;

/**
 * @member {String} avatar
 */
ProfileData.prototype.avatar = undefined;

