/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import SaveTimeIndex from './SaveTimeIndex';

/**
 * The SaveTimeIndexListResponse model module.
 * @module model/SaveTimeIndexListResponse
 * @version v1
 */
export default class SaveTimeIndexListResponse {
  /**
   * Constructs a new <code>SaveTimeIndexListResponse</code>.
   * @alias module:model/SaveTimeIndexListResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SaveTimeIndexListResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SaveTimeIndexListResponse} obj Optional instance to populate.
   * @return {module:model/SaveTimeIndexListResponse} The populated <code>SaveTimeIndexListResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SaveTimeIndexListResponse();
      if (data.hasOwnProperty('success'))
        obj.success = ApiClient.convertToType(data['success'], 'Boolean');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], [SaveTimeIndex]);
    }
    return obj;
  }
}

/**
 * @member {Boolean} success
 */
SaveTimeIndexListResponse.prototype.success = undefined;

/**
 * @member {Array.<module:model/SaveTimeIndex>} data
 */
SaveTimeIndexListResponse.prototype.data = undefined;

