/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Challenge from './Challenge';

/**
 * The Summary model module.
 * @module model/Summary
 * @version v1
 */
export default class Summary {
  /**
   * Constructs a new <code>Summary</code>.
   * @alias module:model/Summary
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Summary</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Summary} obj Optional instance to populate.
   * @return {module:model/Summary} The populated <code>Summary</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Summary();
      if (data.hasOwnProperty('save_version'))
        obj.saveVersion = ApiClient.convertToType(data['save_version'], 'Number');
      if (data.hasOwnProperty('game_version'))
        obj.gameVersion = ApiClient.convertToType(data['game_version'], 'Number');
      if (data.hasOwnProperty('challenge'))
        obj.challenge = Challenge.constructFromObject(data['challenge']);
      if (data.hasOwnProperty('avatar'))
        obj.avatar = ApiClient.convertToType(data['avatar'], 'String');
      if (data.hasOwnProperty('clears'))
        obj.clears = ApiClient.convertToType(data['clears'], ['Number']);
    }
    return obj;
  }
}

/**
 * @member {Number} saveVersion
 */
Summary.prototype.saveVersion = undefined;

/**
 * @member {Number} gameVersion
 */
Summary.prototype.gameVersion = undefined;

/**
 * @member {module:model/Challenge} challenge
 */
Summary.prototype.challenge = undefined;

/**
 * @member {String} avatar
 */
Summary.prototype.avatar = undefined;

/**
 * @member {Array.<Number>} clears
 */
Summary.prototype.clears = undefined;

