/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import TokenData from './TokenData';

/**
 * The TapTapTokenData model module.
 * @module model/TapTapTokenData
 * @version v1
 */
export default class TapTapTokenData {
  /**
   * Constructs a new <code>TapTapTokenData</code>.
   * @alias module:model/TapTapTokenData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TapTapTokenData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TapTapTokenData} obj Optional instance to populate.
   * @return {module:model/TapTapTokenData} The populated <code>TapTapTokenData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TapTapTokenData();
      if (data.hasOwnProperty('data'))
        obj.data = TokenData.constructFromObject(data['data']);
    }
    return obj;
  }
}

/**
 * @member {module:model/TokenData} data
 */
TapTapTokenData.prototype.data = undefined;

