/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import TapTapProfileData from './TapTapProfileData';

/**
 * The TapTapProfileDataResponse model module.
 * @module model/TapTapProfileDataResponse
 * @version v1
 */
export default class TapTapProfileDataResponse {
  /**
   * Constructs a new <code>TapTapProfileDataResponse</code>.
   * @alias module:model/TapTapProfileDataResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TapTapProfileDataResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TapTapProfileDataResponse} obj Optional instance to populate.
   * @return {module:model/TapTapProfileDataResponse} The populated <code>TapTapProfileDataResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TapTapProfileDataResponse();
      if (data.hasOwnProperty('success'))
        obj.success = ApiClient.convertToType(data['success'], 'Boolean');
      if (data.hasOwnProperty('data'))
        obj.data = TapTapProfileData.constructFromObject(data['data']);
    }
    return obj;
  }
}

/**
 * @member {Boolean} success
 */
TapTapProfileDataResponse.prototype.success = undefined;

/**
 * @member {module:model/TapTapProfileData} data
 */
TapTapProfileDataResponse.prototype.data = undefined;

