/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The TokenData model module.
 * @module model/TokenData
 * @version v1
 */
export default class TokenData {
  /**
   * Constructs a new <code>TokenData</code>.
   * @alias module:model/TokenData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TokenData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TokenData} obj Optional instance to populate.
   * @return {module:model/TokenData} The populated <code>TokenData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TokenData();
      if (data.hasOwnProperty('kid'))
        obj.kid = ApiClient.convertToType(data['kid'], 'String');
      if (data.hasOwnProperty('access_token'))
        obj.accessToken = ApiClient.convertToType(data['access_token'], 'String');
      if (data.hasOwnProperty('token_type'))
        obj.tokenType = ApiClient.convertToType(data['token_type'], 'String');
      if (data.hasOwnProperty('mac_key'))
        obj.macKey = ApiClient.convertToType(data['mac_key'], 'String');
      if (data.hasOwnProperty('mac_algorithm'))
        obj.macAlgorithm = ApiClient.convertToType(data['mac_algorithm'], 'String');
      if (data.hasOwnProperty('scope'))
        obj.scope = ApiClient.convertToType(data['scope'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} kid
 */
TokenData.prototype.kid = undefined;

/**
 * @member {String} accessToken
 */
TokenData.prototype.accessToken = undefined;

/**
 * @member {String} tokenType
 */
TokenData.prototype.tokenType = undefined;

/**
 * @member {String} macKey
 */
TokenData.prototype.macKey = undefined;

/**
 * @member {String} macAlgorithm
 */
TokenData.prototype.macAlgorithm = undefined;

/**
 * @member {String} scope
 */
TokenData.prototype.scope = undefined;

