/*
 * PhigrosApi
 * Phigros Api, a plugin wrapper for the wrapper of PhigrosLibraryCSharp
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.71
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The UserInfo model module.
 * @module model/UserInfo
 * @version v1
 */
export default class UserInfo {
  /**
   * Constructs a new <code>UserInfo</code>.
   * @alias module:model/UserInfo
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UserInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserInfo} obj Optional instance to populate.
   * @return {module:model/UserInfo} The populated <code>UserInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserInfo();
      if (data.hasOwnProperty('nickName'))
        obj.nickName = ApiClient.convertToType(data['nickName'], 'String');
      if (data.hasOwnProperty('userName'))
        obj.userName = ApiClient.convertToType(data['userName'], 'String');
      if (data.hasOwnProperty('creationTime'))
        obj.creationTime = ApiClient.convertToType(data['creationTime'], 'Date');
      if (data.hasOwnProperty('modificationTime'))
        obj.modificationTime = ApiClient.convertToType(data['modificationTime'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {String} nickName
 */
UserInfo.prototype.nickName = undefined;

/**
 * @member {String} userName
 */
UserInfo.prototype.userName = undefined;

/**
 * @member {Date} creationTime
 */
UserInfo.prototype.creationTime = undefined;

/**
 * @member {Date} modificationTime
 */
UserInfo.prototype.modificationTime = undefined;

